### ISSUE TITLE
PendingDeprecationWarning with Python 3.4.1

### ISSUE THREAD

**Issue by quicklizard99** [python-excel/xlrd#104]
Running 

    python -m unittest discover

with python 3.4.1 gives:

    /Users/lawh/build/xlrd/xlrd/xlsx.py:246: PendingDeprecationWarning: This method will be removed in future versions.  Use 'tree.iter()' or 'list(tree.iter())' instead.
        for elem in self.tree.getiterator():
    /Users/lawh/build/xlrd/xlrd/xlsx.py:292: PendingDeprecationWarning: This method will be removed in future versions.  Use 'tree.iter()' or 'list(tree.iter())' instead.
      for elem in self.tree.getiterator():

I have submitted a pull request that fixes the warnings.

**Comment by cjw296** [comment]
Merged and fixed in 1.0.1
