### ISSUE TITLE
Cell note in second sheet gets read as being in first sheet

### ISSUE THREAD

**Issue by gthb** [python-excel/xlrd#108]
In Excel, make an `.xlsx` file (can't attach one here) with two sheets, put a cell comment in the second sheet. Then:

```
from xlrd import *
b = open_workbook('xlrd-note-bug.xlsx')
assert b.sheets()[1].cell_note_map == {}
assert b.sheets()[0].cell_note_map != {}
```

The two assertions pass, and they shouldn't. The non-empty cell note map should be on the second sheet.

**Comment by cjw296** [comment]
I'll merge #116 so closing this for now.
