### ISSUE TITLE
CSV Translator

### ISSUE THREAD

**Issue by uvenkatesh** [python-excel/xlrd#114]
Is there a sample tool for converting XLS files to CSV?

**Comment by mgrazebrook** [comment]
#!/c/Anaconda3/python.exe
"""
Convert an Excel file to a csv file .
"""
# Thoughts for enhancements:
# Export all sheets in each excel file (a foreach on sheets - file names sort themselves out)
# Command line option to export a specific sheet
# Command line option to export only a box-shaped array of cells (e.g. a table within a sheet)
# Ability to somehow get option 'xmlcharrefreplace' into the file open() so it doesn't die on encountering an illegal character

import xlrd
import csv
import os.path
import datetime
import sys

def value(cell, book):
    if cell.ctype in (0, 6):
        return ""
    if cell.ctype in (2,):
        # int or float?
        if int(cell.value) == cell.value:
            return int(cell.value)
        return cell.value
    if cell.ctype in (1, 4):
        return cell.value
    if cell.ctype == 3:
        frac = (cell.value % 1) * 24 * 60 * 60 % 1
        year, month, day, hour, minute, nearest_second = xlrd.xldate_as_tuple(cell.value, book.datemode)

        ret= datetime.datetime( year, month, day, hour, minute, nearest_second, int(frac * 1000000))
        
        if round(frac) == 1:
            ret -= datetime.timedelta(seconds=1)

        return ret


def convert_file(excel_file_name, sheet_name = None):
    """
    Convert one sheet of an Excel file to csv. 
    
    By default, convert the first sheet.
    """
    book = xlrd.open_workbook(excel_file_name)
    if sheet_name == None:
        sheet = book.sheet_by_index(0)
    else:
        sheet = book.sheet_by_name(sheet_name)
        
    out_file_name = os.path.splitext(excel_file_name)[0] + '.' + sheet.name + '.csv'
    with open(out_file_name, "w", newline='') as csvfile:
        out = csv.writer(csvfile)
        for row in range(sheet.nrows):
            out_row = [ value(sheet.cell(row, col), book) for col in range(sheet.ncols)]

            out.writerow(out_row)

if __name__ == '__main__':
    for file_name in sys.argv[1:]:
        convert_file(file_name)
