### ISSUE TITLE
Named references not working in .xlsx files

### ISSUE THREAD

**Issue by pallih** [python-excel/xlrd#119]
Output from  xlrdnameAPIdemo.py in https://github.com/python-excel/xlrd/tree/master/xlrd/examples

python xlrdnameAPIdemo.py "namesdemo.xls" "*" "*" "1"

    Name: u'A1Z10', scope: -1 (Global)
    Formula eval result: Operand(kind=oREL, value=[Ref3D(coords=(2, 3, 0, -16, 0, 26), relflags=(0, 0, 0, 1, 0, 0))], text=u'Sheet3!R1C1:R[-17]C26')
    Range 0: (2, 3, 0, -16, 0, 26) ==> u'Sheet3!R1C1:R[-17]C26'

    Name: u'addnumstr', scope: -1 (Global)
    Formula eval result: Operand(kind=oNUM, value=579.0, text=u'123.0+"456"')

etc.

Same test file saved as .xlsx:

    python xlrdnameAPIdemo.py "name*.xlsx" "*" "*" "1"

    Name: u'A1Z10', scope: -1 (Global)
    Formula eval result: None

    Name: u'addnumstr', scope: -1 (Global)
    Formula eval result: None

etc.

See also this SO thread: https://stackoverflow.com/questions/3163073/how-to-locate-and-access-named-ranges-global-nd-per-worksheet-using-xlrd-pyt

**Comment by cjw296** [comment]
I'm afraid that without a pull request including unit tests to fix this, it's unlikely to change.
