### ISSUE TITLE
error reading xls files saved by libreoffice

### ISSUE THREAD

**Issue by raforg** [python-excel/xlrd#121]
I usually get the following error when using xlrd-0.9.3 to try to read an xls file that has been saved
by LibreOffice-4.3.2.2. It has never happened for me with xls files saved by OpenOffice.

Github won't let me attach an example xls file here so I've placed one temporarily at:

  http://raf.org/tmp/xls-saved-by-libreoffice-that-xlrd-cannot-read.xls

*** ERROR Unexpected data at end of OBJECT record
    0:      00 00 00 00 ff ff ff ff ff ff ff ff ff ff ff ff  ~~~~????????????
   16:      ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ????????????????
   32:      ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ????????????????
   48:      ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ????????????????
   64:      ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ????????????????
   80:      ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ????????????????
   96:      ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ????????????????
  112:      ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ????????????????
  128:      ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ????????????????
  144:      ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ????????????????
  160:      ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ????????????????
  176:      ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ????????????????
  192:      ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ????????????????
  208:      ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ????????????????
  224:      ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ????????????????
  240:      ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ????????????????
  256:      ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ????????????????
  272:      ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ????????????????
  288:      ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ????????????????
  304:      ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ????????????????
  320:      ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ????????????????
  336:      ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ????????????????
  352:      ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ????????????????
  368:      ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ????????????????
  384:      ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ????????????????
  400:      ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ????????????????
  416:      ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ????????????????
  432:      ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ????????????????
  448:      ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ????????????????
  464:      ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ????????????????
  480:      ff ff ff ff ff ff ff ff 01 00                    ?????????~
Traceback (most recent call last):
  File "/Users/raf/bin/xls2csv", line 190, in <module>
    main()
  File "/Users/raf/bin/xls2csv", line 186, in main
    for row in reader(sys.argv[1], i):
  File "/Users/raf/bin/xls2csv", line 128, in reader
    book = xlrd.open_workbook(fname, formatting_info=True)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/xlrd/__init__.py", line 435, in open_workbook
    ragged_rows=ragged_rows,
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/xlrd/book.py", line 119, in open_workbook_xls
    bk.get_sheets()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/xlrd/book.py", line 678, in get_sheets
    self.get_sheet(sheetno)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/xlrd/book.py", line 669, in get_sheet
    sh.read(self)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/xlrd/sheet.py", line 1079, in read
    saved_obj = self.handle_obj(data)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/xlrd/sheet.py", line 1893, in handle_obj
    raise XLRDError(msg)
xlrd.biffh.XLRDError: Unexpected data at end of OBJECT record

**Comment by jvc26** [comment]
Yup, same problem here!

**Comment by douglasanr** [comment]
same here...  any idea ?

**Comment by scraperdragon** [comment]
I took an xlsx file, added some rich text fields, saved as xlsx; then later converted to xls with LibreOffice 4.3.3.2 430m0(Build:2) on ubuntu - broken. Converting that same file with LibreOffice 4.2.6.3 on Mac worked fine - at least, it got past open_workbook fine.

Possibly a regression in LibreOffice.

**Comment by tonal** [comment]
Same problem:
```
$ wget http://www.enr34.ru/upload/price/groppalli.xls
$ python -c 'import xlrd; xlrd.open_workbook("groppalli.xls")' 
*** ERROR Unexpected data at end of OBJECT record
    0:      00 00 00 00 ff ff ff ff ff ff ff ff ff ff ff ff  ~~~~????????????
   16:      ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ????????????????
   32:      ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ????????????????
   48:      ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ????????????????
   64:      ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ????????????????
   80:      ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ????????????????
   96:      ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ????????????????
  112:      ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ????????????????
  128:      ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ????????????????
  144:      ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ????????????????
  160:      ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ????????????????
  176:      ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ????????????????
  192:      ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ????????????????
  208:      ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ????????????????
  224:      ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ????????????????
  240:      ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ????????????????
  256:      ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ????????????????
  272:      ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ????????????????
  288:      ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ????????????????
  304:      ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ????????????????
  320:      ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ????????????????
  336:      ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ????????????????
  352:      ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ????????????????
  368:      ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ????????????????
  384:      ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ????????????????
  400:      ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ????????????????
  416:      ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ????????????????
  432:      ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ????????????????
  448:      ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ????????????????
  464:      ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ????????????????
  480:      ff ff ff ff ff ff ff ff ff ff                    ??????????
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 435, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 119, in open_workbook_xls
    bk.get_sheets()
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 678, in get_sheets
    self.get_sheet(sheetno)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 669, in get_sheet
    sh.read(self)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/sheet.py", line 1079, in read
    saved_obj = self.handle_obj(data)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/sheet.py", line 1893, in handle_obj
    raise XLRDError(msg)
xlrd.biffh.XLRDError: Unexpected data at end of OBJECT record
```
Bat groppalli.xls open in LibreOffice 4.4.1.2

**Comment by tonal** [comment]
How to workaround for this event?

**Comment by scraperdragon** [comment]
Commenting out the `raise` statement at https://github.com/python-excel/xlrd/blob/master/xlrd/sheet.py#L1893 *appears* to give meaningful results.

Wouldn't trust this at all... but might be of use to you.

**Comment by cjw296** [comment]
If someone could work up a pull request that includes unit tests, it would be great to see this fixed.
Sadly, closing in the meantime.
