### ISSUE TITLE
Error while reading a named cell in excel 2007 xlsx file

### ISSUE THREAD

**Issue by gryken2014** [python-excel/xlrd#122]
xlrd-0.9.3 / windows 7 64bits / python 3.2 32bits

I've created 2 excel files : test_testname.xls and test_testname.xlsx
Each of them have a cell named 'TestName', in the first sheet, in B:2

The cell is fill with the string "Bibi"

I try to read it in xls file and in xlsx file, with the following code :
#-------------------------------------------------------------------------------------------------------
import xlrd

book_1 = xlrd.open_workbook("test_testname.xls")
book_2 = xlrd.open_workbook("test_testname.xlsx")
name_1 = book_1.name_map.get("TestName".lower())[0]
name_2 = book_2.name_map.get("TestName".lower())[0]
print("name_1.result:", name_1.result)  # name_1.result: Operand(kind=oREF, value=[Ref3D(coords=(0, 1, 1, 2, 1, 2))], text='Feuil1!$B$2')
print("name_2.result:", name_2.result)  # name_2.result: None

print(name_1.cell())  # prints text:'Bibi'

print(name_2.cell())  # fail here
#-------------------------------------------------------------------------------------------------------

- The XLS can be read.

- But the XLSX fail with the traceback :

Traceback (most recent call last):
  File "test.py", line 23, in <module>
    print(name_2.cell())
  File "..\..\xlrd\book.py", line 253, in cell
    self.dump(self.book.logfile,
AttributeError: 'NoneType' object has no attribute 'logfile'

After some research, this problem is already reported here:
  
- http://stackoverflow.com/questions/25640549/xlrd-named-range-not-working-for-excel-2013-workbooks

- http://stackoverflow.com/questions/15937493/accessing-the-value-of-the-intersection-of-named-ranges-of-an-excel-spreadsheet

I tried to use xlrdnameAPIdemo.py.

- with XLS file, it extract the cell name (TestName), and the value (string Bibi)
- with XLSX file, it extract the cell name, but without value...

, is it a bug or not ?
- is there a bug in my code ?
- If not, how to read the value of a named cell in a XLSX file ?

It seems to be close of #119

Thanks for xlrd.

**Comment by cjw296** [comment]
Could you try again with 1.0.1?
If suspect it probably won't be any better, and without a pull request, this is unlikely to see any progress.
