### ISSUE TITLE
Is there a way to pass file-like object to function open_workbook?

### ISSUE THREAD

**Issue by hexum** [python-excel/xlrd#124]
Hi!

I get xlsx file from net by URL. I don't want to save temp file and trying to pass buffer with data to open_workbook.
Is there a clear way to do it?

**Comment by ErikEvenson** [comment]
How about something like:

```
workbook = xlrd.open_workbook(file_contents=f.read()
```

**Comment by hexum** [comment]
I think open_workbook() opens file descriptor to read the file. Adding
simple check of incoming object type may resolve issue.
If incoming object is file-like (has read() method), then use it as already
opened file.
But if there are some difficulties any method is acceptable.
Thanks!
05.02.2015 5:36 пользователь "Erik Evenson" <notifications@github.com>
написал:

**Comment by natw** [comment]
If you don't mind loading the entire file into memory up front, it looks like `xlrd.open_workbook(file_contents=f.read())` works (assuming `f` is the file-like object you have).

**Comment by cjw296** [comment]
This is not a mailing list, please take this discussion to the python-excel list.
