### ISSUE TITLE
empty xls sheet import error

### ISSUE THREAD

**Issue by skilus** [python-excel/xlrd#136]
If sheet is empty it doesn't iterate counter while xls import
We had 5 sheets, 3rd was empty, and we tried to get 4th sheet, but imported data was from 5th

**Comment by sjmachin** [comment]
Please (1) send me a copy of the xls file if possible (2) provide a short Python script that illustrates the problem

**Comment by skilus** [comment]
1) https://drive.google.com/file/d/0B9oXeHuRJ8B3ZThnVjZjREFOckk/view?usp=sharing
2) Actually it's not python but node.js script, this one https://github.com/extrabacon/pyspreadsheet

**Comment by cjw296** [comment]
Your 2) won't help @sjmachin, please provide a short Python script.

**Comment by sjmachin** [comment]
Re 1) Yes, you are correct, the third worksheet has no data in it, according to xlrd's runxlrd.py script.
Re 2) You should address your problem to the extrabacon project -- evidently it uses javascript to run a Python script (excel_reader.py) which uses xlrd and writes a JSON object to stdout for each file, sheet, and cell. I have tried running excel_reader.py on my tiny test file and your large file (args: -r1 afile.xls) ... -r1 means print only 1 row per sheet ... and it worked as expected i.e. no cells emitted from the 3rd sheet, next sheet's data correctly ascribed to the 4th sheet, likewise 5th sheet was OK.
I can't help you with the javascript code.
