### ISSUE TITLE
Key error on xlrd.open_workbook

### ISSUE THREAD

**Issue by jaamiller** [python-excel/xlrd#150]
I have some XLSX files produced from a 3rd party database export tool.
I get a failure, as below when I attempt to import them to xlrd.

KeyError: u'xl/worksheets/Sheet1.xml'

This is because the tool creates a file called xl/worksheets/Sheet1.xml (upper case S) AND references it in xl/_rels/workbook.xml.rels as the target for 'rId1'

If I unzip the xlsx file, and alter the file xl/_rels/workbook.xml.rels
Target="worksheets/Sheet1.xml"
to
Target="worksheets/sheet1.xml"
(Changing case)
...I can eliminate the error.

Just renaming xl/worksheets/Sheet1.xml to xl/worksheets/sheet1.xml does not solve the problem

XLRD seems to infer the key names in the zip component names, rather than deducing them from info in the xslx file.
Is this an error, or expected behaviour?

If I raise the logging error to 3, I get output that includes values from the worksheet, so XLRD can apparently still read the file, despite generating this error.

==== Code ====
workbook = xlrd.open_workbook(xls_infile, verbosity=2 )

==== ERROR Follows ====
ZIP component_names:
{'[content_types].xml': '[Content_Types].xml',
 '_rels/.rels': '_rels/.rels',
 'docprops/app.xml': 'docProps/app.xml',
 'docprops/core.xml': 'docProps/core.xml',
 'xl/_rels/workbook.xml.rels': 'xl/_rels/workbook.xml.rels',
 'xl/sharedstrings.xml': 'xl/sharedStrings.xml',
 'xl/styles.xml': 'xl/styles.xml',
 'xl/workbook.xml': 'xl/workbook.xml',
 'xl/worksheets/sheet1.xml': 'xl/worksheets/Sheet1.xml'}

=== Relationships ===
            Id='rId1' Type=u'worksheet' Target='worksheets/Sheet1.xml'
            Id='rId2' Type=u'styles' Target='styles.xml'
            Id='rId3' Type=u'sharedStrings' Target='sharedStrings.xml'

=== Workbook ===
            datemode=0
            sheetx=0 sheetId=1 rid='rId1' type=u'worksheet' name=u'Page1_1'

=== coreProps ===
props: {}

=== styles ===

=== SST ===
            Entries in SST: 74378
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-28-3758e9a21b21> in <module>()
     11 
     12 
---> 13 workbook = xlrd.open_workbook(xls_infile, verbosity=2 )
     14 
     15 

/Library/Python/2.7/site-packages/xlrd/__init__.pyc in open_workbook(filename, logfile, verbosity, use_mmap, file_contents, encoding_override, formatting_info, on_demand, ragged_rows)
    420                 formatting_info=formatting_info,
    421                 on_demand=on_demand,
--> 422                 ragged_rows=ragged_rows,
    423                 )
    424             return bk

/Library/Python/2.7/site-packages/xlrd/xlsx.pyc in open_workbook_2007_xml(zf, component_names, logfile, verbosity, use_mmap, formatting_info, on_demand, ragged_rows)
    788     for sheetx in range(bk.nsheets):
    789         fname = x12book.sheet_targets[sheetx]
--> 790         zflo = zf.open(component_names[fname])
    791         sheet = bk._sheet_list[sheetx]
    792         x12sheet = X12Sheet(sheet, logfile, verbosity)

KeyError: u'xl/worksheets/Sheet1.xml'

**Comment by cjw296** [comment]
I think this has been fixed, please re-open if you can reproduce on lastest master.

**Comment by jaamiller** [comment]
It is indeed fixed in Master.
Cheers

**Comment by finoptimal-dev** [comment]
Is it fixed in the latest release? I'm using 0.9.4 and still getting this error.

**Comment by Karikari** [comment]
am getting this error too

**Comment by cjw296** [comment]
Use the latest release.
