### ISSUE TITLE
Workbook corruption

### ISSUE THREAD

**Issue by alessss** [python-excel/xlrd#153]
Hello!
Sometimes Iget such an error as below. The file looks valid and can be opened in Excel. Some files work ok, but some can't be opened. All the files look ok. xlrd lib version is 0.9.4

_locate_stream(Workbook): seen
    0  5 4 4 4 4 4 4 4 4 4 4 3 2 
Traceback (most recent call last):
  File "C:/Users/a_makarevich/PycharmProjects/Stock/minfin_checker.py", line 94, in <module>
    get_market_price2(n)
  File "C:/Users/a_makarevich/PycharmProjects/Stock/minfin_checker.py", line 66, in get_market_price2
    wb = xlrd.open_workbook(fname)
  File "C:\Python27\lib\site-packages\xlrd\__init__.py", line 441, in open_workbook
    ragged_rows=ragged_rows,
  File "C:\Python27\lib\site-packages\xlrd\book.py", line 87, in open_workbook_xls
    ragged_rows=ragged_rows,
  File "C:\Python27\lib\site-packages\xlrd\book.py", line 592, in biff2_8_load
    cd.locate_named_stream(UNICODE_LITERAL(qname))
  File "C:\Python27\lib\site-packages\xlrd\compdoc.py", line 390, in locate_named_stream
    d.tot_size, qname, d.DID+6)
  File "C:\Python27\lib\site-packages\xlrd\compdoc.py", line 418, in _locate_stream
    raise CompDocError("%s corruption: seen[%d] == %d" % (qname, s, self.seen[s]))
xlrd.compdoc.CompDocError: Workbook corruption: seen[2] == 4

**Comment by jycxmu** [comment]
I also met this problem, and find one way to solve it:
The xls doc I used is down from webpage, I open it with excel and saved it as another .xls doc. Then xlrd can open the new .xls correctly.
I don't know why, but it works.

**Comment by tonal** [comment]
See also #149 and http://stackoverflow.com/a/19997217

**Comment by tonal** [comment]
And #66

**Comment by tonal** [comment]
And also http://stackoverflow.com/questions/16618672/xlrd-crashes-when-reading-xls-file-modified-by-phpexcel

**Comment by cjw296** [comment]
xlrd doesn't handle this broken data.

If you'd like it to, please submit a pull request including lot of unit tests to demonstrate the problems and how your code changes handle them.

**Comment by TrinhDinhPhuc** [comment]
jycxmu that's great!

**Comment by ConstantSun** [comment]
> I also met this problem, and find one way to solve it:
> The xls doc I used is down from webpage, I open it with excel and saved it as another .xls doc. Then xlrd can open the new .xls correctly.
> I don't know why, but it works.

THANK YOU SO SO MUCH!!!
omg!!! i spent 1 hour to try to open xls file and your suggest works like MAGIC !@! Problem like this drives me crazy !!! Like wtf is going on .... just save it as a new file and IT WORKS !?! i still not understand wtf is goin on

**Comment by Nelson-Gon** [comment]
This is dumb but I was actually reading a csv with read_excel. Don't do that.

**Comment by potem** [comment]
Is there a permanent fix to the issue? Without resaving it in Excel?

**Comment by jycxmu** [comment]
Sorry I have no idea this time

发自我的 iPhone

在 2019年5月29日，下午6:50，Tom Petri <notifications@github.com<mailto:notifications@github.com>> 写道：


Is there a permanent fix to the issue? Without resaving it in Excel?
