### ISSUE TITLE
BUG:  XLS files saved by Excel 2013 on Windows cause AssertionError

### ISSUE THREAD

**Issue by Dr-Irv** [python-excel/xlrd#154]
I was doing some testing of pandas and saved the same file as an XLSX and an XLS file for unit testing.  On Windows, I use Excel 2013. I need the XLS file to test Pandas.

Here is the bug in xlrd 0.9.3 that I found.  I start with an XLSX file on Windows with Excel 2013.  That is attached as xlrdtest.xlsx.  That file reads fine with xlrd.
I then use Excel 2013 to save the file as an XLS file (so that I can test it with pandas unit testing).  That file is attached as xlrdtest.xls .  That file fails to read in with xlrd:

```
>>> wk = xlrd.open_workbook("xlrdtest.xls")
*** formula/tFunc unknown FuncID:186
*** formula/tFunc unknown FuncID:186
*** formula/tFunc unknown FuncID:186
*** formula/tFunc unknown FuncID:186
*** formula/tFunc unknown FuncID:186
*** formula/tFunc unknown FuncID:186
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3035, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-16-eb22c9b75a70>", line 1, in <module>
    wk = xlrd.open_workbook("xlrdtest.xls")
  File "C:\Anaconda3\lib\site-packages\xlrd\__init__.py", line 435, in open_workbook
    ragged_rows=ragged_rows,
  File "C:\Anaconda3\lib\site-packages\xlrd\book.py", line 116, in open_workbook_xls
    bk.parse_globals()
  File "C:\Anaconda3\lib\site-packages\xlrd\book.py", line 1198, in parse_globals
    self.names_epilogue()
  File "C:\Anaconda3\lib\site-packages\xlrd\book.py", line 997, in names_epilogue
    evaluate_name_formula(self, nobj, namex, blah=blah)
  File "C:\Anaconda3\lib\site-packages\xlrd\formula.py", line 1125, in evaluate_name_formula
    assert len(tgtobj.stack) == 1
AssertionError
```

I then transfer the XLSX file xlrdtest.xlsx to a Mac, and use Excel Mac 2011 to read in that file and save it as an XLS file.  That is attached as xlrdtestMac.xls.  That file reads in fine with xlrd.

So it seems the problem is with how the Windows version of Excel is saving the file.

Note that it is the presence of multiple worksheets that seems to trigger the exception.  If the original XLSX file has one sheet, then the Excel 2013 saved XLS file reads in fine.

The test files to reproduce this can be found on Google Groups here:
https://groups.google.com/forum/#!topic/python-excel/XeX07px4La0

**Comment by tystakartografen** [comment]
I had exactly the same error earlier today. After further investigation xlrd was trying to evaluate formula names such as LOCAL_DATE_SEPARATOR, LOCAL_DAY_FORMAT and LOCAL_HOUR_FORMAT. It turns out that the MySQL Excel COM add-on that is a component included in the MySQL Workbench package was adding extra meta data. Disabling this add-on fixed the issue.

**Comment by ct0820** [comment]
Can you tell me the way how to solve this problem?Appreciatively~

**Comment by jiteshanand** [comment]
I also got the same error.Any tested solution till now?

Thanks!

**Comment by cjw296** [comment]
Sounds like the solution is to disable the MySQL Excel COM add-on.

**Comment by Dr-Irv** [comment]
I tried disabling that add-in and it didn't fix the problem.

**Comment by cjw296** [comment]
I'm sorry to hear that. If you can provide a pull request including unit tests with a fix, I'd be happy to merge.

**Comment by Dr-Irv** [comment]
I have no idea how to fix it.  The tests I created can be found here: 
https://groups.google.com/forum/#!topic/python-excel/XeX07px4La0

Are you not able to replicate?

**Comment by cjw296** [comment]
I have no idea either. Someone needs to do the work, that someone is unlikely to be me.

**Comment by Dr-Irv** [comment]
Can  you reopen this issue, so at least other maintainers are aware?

**Comment by cjw296** [comment]
@sjmachin is the only other maintainer and he's aware.

Curious: what's stopping you use openpyxl?

**Comment by cjw296** [comment]
But sure, I'll just leave this here and see if anyone comes along to fix...

**Comment by Dr-Irv** [comment]
I'm using pandas to read the Excel file, and xlrd is the only supported reader there (as best as I can tell)

**Comment by xiaogaobo** [comment]
I got the same exception. Anyone fix..?

**Comment by arorpee** [comment]
Hello Guys I have fixed this issue, please follow the steps:
1. Please go to this location where your python folder is like 
C:\Python27\Lib\site-packages\xlrd  

2. Open formula.py

3.  after line 184 in the file please add this 186 line

184: ('FACT', 1, 1, 0x02, 1, 'V', 'V'),
186: ('HACKED', 1, 1, 0x02, 1, 'V', 'V'), 
189: ('DPRODUCT', 3, 3, 0x02, 3, 'V', 'RRR'), 


4. Re run your main program and I hope now its working fine!

**Comment by NimaP** [comment]
aropee's solution worked for my python 3, (anaconda 4.4.11 on windows). I had to go here:
\AppData\Local\Continuum\Anaconda3\Lib\site-packages\xlrd

**Comment by timluther** [comment]
Thanks for the fix, solved my problem.
@arorpee: any chance of getting that fix in to the repros?

**Comment by cjw296** [comment]
Is there a PR open for this? Closing until someone pipes up.
