### ISSUE TITLE
README is outdated and gives a bad impression of the project

### ISSUE THREAD

**Issue by vog** [python-excel/xlrd#158]
The main README in `master` as visible on GitHub shows the following misleading bits of information:

> Version of xlrd: 0.7.1 -- 2009-05-31
> Versions of Excel supported: [...]. Support for Excel 2007 .xlsx files scheduled for version 0.7.1.

This gives a really bad first impression of the project.

It reads as if development stopped in 2009 and as if it can't really read `.xlsx` files yet. Only a second look at the commits and the releases reveals that development is very active and that this is currently at `0.9.4`.

**Comment by cjw296** [comment]
You ever consider this might be deliberate? ;-)
