### ISSUE TITLE
Incorrect comment: Empty cell is not used as singleton

### ISSUE THREAD

**Issue by vog** [python-excel/xlrd#162]
One comment in `sheet.py` states that `xlrd.sheet.empty_cell` is used as singleton:

> There is one and only one instance of an empty cell -- it's a singleton. This is it.
> You may use a test like "acell is empty_cell".

https://github.com/python-excel/xlrd/blob/7db25ab798a66a18ed92eaed000f3c1a6bcc21db/xlrd/sheet.py#L2266-L2268

However, this information is incorrect.

For example, if you add the following assertion to the `test_empty_cell` test (defined in `tests/test_cell.py`), that test will fail:

    self.assertTrue(cell is xlrd.sheet.empty_cell)

I'm not sure if this is a bug in the code or in the comment/documentation, though.

**Comment by cjw296** [comment]
Hmm, it should be a singleton. Any chance you could uncover why it's not? @sjmachin : views?

**Comment by vog** [comment]
Well, the reason is very simple: Internally, the Sheet doesn't store Cell instances in the first place.

Instead, the cells are stored in two arrays `_cell_types` and `_cell_values`, which isn't bad, as that will save a lot of RAM for large sheets. Actual Cell instances are only created when calling `Sheet.cell()`.

Moreover, there are methods `put_cell_ragged()` and `put_cell_unragged()` which take a cell type and value and add multiple instances to fill gaps. I had to fix all those to in commit 7e19d88bda9a0016815142e0d71712d8adac7923, too, to make the test pass. So this is another point where multiple empty cells are created.

I see two possibilities to solve this

1. Change `Sheet.cell()` to return the `empty_cell` singleton instead of creating a new cell.
2. Give up the concept of an `empty_cell` singleton, as that doesn't exist internally. (So there is almost gain in memory or performance in the `Sheet` class by introducing it on top of `Sheet.cell()`.)

**Comment by cjw296** [comment]
Hmm, 7e19d88 doesn't contain any changes I'd expect to see in relation to this.

That said, my suggestion would be to punt on this until @sjmachin gets a chance to take a look. My gut feel is that the comment should probably go away, but there might be an important reason for it being a singleton that I'm unaware of.

Shouldn't hold up any of your changes, though...

**Comment by sjmachin** [comment]
The comment should go away. There seems to be no advantage in making empty_cell a singleton. This area has not changed since as far back as I could conveniently check i.e. version 0.9.1 in May 2009.

**Comment by cjw296** [comment]
@vog - we have an answer! If you could do a pull request to get rid of the comment, that would be great!

**Comment by vog** [comment]
Done.
