### ISSUE TITLE
Allow for all cell values to be read as XL_CELL_TEXT instead

### ISSUE THREAD

**Issue by kelvintaywl** [python-excel/xlrd#166]
Is is possible to perhaps, allow an option, in `open_workbook` to say that I would like to have all cell values to be of `XL_CELL_TEXT` type instead?

The reason is because, when one of the cell is just a whole number, the value is read as of `XL_CELL_NUMBER` type and doing a `str(cell.value)` results in a stringified float representation (e.g, `5.0`), which is not ideal for me.

**Comment by cjw296** [comment]
No. The values are stored in their type, so then xlrd would have to guess for you.
