### ISSUE TITLE
self._cell_values[rowx][colx] -> IndexError: list index out of range

### ISSUE THREAD

**Issue by chfw** [python-excel/xlrd#167]
Hi, folks:

Is there anything you can help fix this error? The xlsx file can be downloaded from [github Test2.xlsx](https://github.com/pyexcel/pyexcel/files/105092/Test2.xlsx). This issue was originally reported in this library https://github.com/pyexcel/pyexcel/issues/20

    >>> import xlrd
    >>> wb=xlrd.open_workbook("Test2.xlsx", on_demand=True)
    >>> s=wb.sheet_by_index(0)
    >>> for r in range(0, s.nrows):
    ...     for c in range(0, s.ncols):
    ...         print s.cell_value(r,c)
    Traceback (most recent call last):
      File "<stdin>", line 3, in <module>
      File "/cygdrive/c/bbc/myenv/lib/python2.7/site-packages/xlrd/sheet.py", line 407, in cell_value
        return self._cell_values[rowx][colx]
    IndexError: list index out of range

Cheers

**Comment by ankur0493** [comment]
Your Excel file is not formatted properly. There are actually 21 columns with text, but xlrd is reading the number of columns as 23 because of undesired merging of columns. Correct that and you are good to go.

**Comment by chfw** [comment]
openpyxl can tolerate such an error so would xlrd do the same? The practical problem is: sometimes, the owner of the excel sheet is not really a IT pro but a IT-novice with high stake(e.g. a project sponsor) in a critical(critical to a developer) IT project.

**Comment by cjw296** [comment]
If openpyxl can tolerate it, why not use openpyxl?

**Comment by chfw** [comment]
Good suggestion.
