### ISSUE TITLE
IndexError: list out of range - self._cell_types[rowx][colx] = ctype in put_cell_unragged

### ISSUE THREAD

**Issue by SteepCliff** [python-excel/xlrd#168]
[TestFile.xlsx](https://github.com/python-excel/xlrd/files/108034/TestFile.xlsx)
When trying opening the workbook attached with xlrd.open_workbook("TestFile.xlsx"), xlrd generate an error with the following message:
sheet.py, line 685, in put_cell_unragged
self._cell_types[rowx][colx] = ctype
IndexError: list index out of range
It also raised a MemoryError when handling this exception.

Important note, in the excel file, there is some data in the last columns of the sheet, when I delete these columns in the file, the error in not raised.
I tried to raise the error unsuccessfully with a blank excel file and by adding some data in the first and in the last columns.

Any ideas?

I am using Python 3.5 and xlrd-0.9.4

**Comment by sjmachin** [comment]
There is also data in the last row:
cell A1048511: type=0, data: ''
cell B1048511: type=1, data: u'PARIS'
This is the real cause of the problem.

use open_workbook(..., ragged_rows=True)

Docs for ragged_rows arg:
    False (the default) means all rows are padded out with empty cells so that all rows have the same size (Sheet.ncols). True means that there are no empty cells at the ends of rows. This can result in substantial memory savings if rows are of widely varying sizes. See also the Sheet.row_len() method. 

Docs for Sheet.row_len():
row_len(rowx) [#]

Returns the effective number of cells in the given row.
For use with open_workbook(ragged_rows=True)
which is likely to produce rows
with fewer than ncols cells.

**Comment by SteepCliff** [comment]
It works successfully. Thank you very much for the explanation. 

Just for a confirmation, as there is no mean to know how the excel file is filled before I open it, and  if I don't want to raise an error that I am not able to handle, I need to always use open_workbook(file, ragged_row=True).

_Bonus question:_ why the default option is False then? (I am probably asking this question because of my lack of knoweldge of xlrd library... well, there is no stupid question, isn't it? ) 

Anyway, my problem is solved, thank you again.

**Comment by sjmachin** [comment]
Instead of s.ncols, use s.row_len(row_index)

**Comment by SteepCliff** [comment]
Thank you
