### ISSUE TITLE
Font.underlined and Font.bold not being populated

### ISSUE THREAD

**Issue by VBaratham** [python-excel/xlrd#170]
Documentation says that [Font.bold](https://secure.simplistix.co.uk/svn/xlrd/trunk/xlrd/doc/xlrd.html?p=4966#formatting.Font.bold-attribute) and [Font.underlined](https://secure.simplistix.co.uk/svn/xlrd/trunk/xlrd/doc/xlrd.html?p=4966#formatting.Font.underlined-attribute) are redundant with Font.weight and Font.underline_type, respectively, but I'm seeing Font instances that have one but not the other, eg:

```
In [60]: wb.font_list[5].dump()
bold: 0
character_set: 1
colour_index: 8
escapement: 0
family: 2
font_index: 5
height: 240
italic: 0
name: u'Calibri'
outline: 0
shadow: 0
struck_out: 0
underline_type: 0
underlined: 0
weight: 400

In [61]: wb.font_list[8].dump()
bold: 0
character_set: 1
colour_index: 8
escapement: 0
family: 2
font_index: 8
height: 240
italic: 0
name: u'Calibri'
outline: 0
shadow: 0
struck_out: 0
underline_type: 1
underlined: 0
weight: 700
```

**Comment by cjw296** [comment]
I don't really know what to tell you... Either the documentation or the code is wrong, but pull requests are needed for both...

**Comment by VBaratham** [comment]
Am I not supposed to open an issue unless I already have a fix? If either code or documentation is wrong, shouldn't this issue stay open?
