### ISSUE TITLE
Out of the box xlrd is vulnerable to XML external entity attacks

### ISSUE THREAD

**Issue by dmr** [python-excel/xlrd#173]
This is not really an issue but rather something I wish I found when I looked into the github of this project:
If you use open_workbook with standard configuration then your app is vulnerable to XEE attacks:
https://en.wikipedia.org/wiki/Billion_laughs

There is a project that helps with the prevention of this: https://pypi.python.org/pypi/defusedxml

This is how we use it. We wrap every call of open_workbook:

```
import defusedxml
from defusedxml.common import EntitiesForbidden
from xlrd import open_workbook
defusedxml.defuse_stdlib()


def secure_open_workbook(**kwargs):
    try:
        return open_workbook(**kwargs)
    except EntitiesForbidden:
        raise ValueError('Please use a xlsx file without XEE')
```

Anybody else had this problem yet? Is it worth to mention is somewhere in the docs?

**Comment by cjw296** [comment]
Agreed on the docs, might be worth also raising this on https://bitbucket.org/openpyxl/openpyxl/issues?status=new&status=open.

Honestly, openpyxl is the library I'd recommend for dealing with Excel files, as long as you don't have to deal with .xls.
