### ISSUE TITLE
doc is misusing the term "unicode"

### ISSUE THREAD

**Issue by deronnax** [python-excel/xlrd#178]
In [docs/unicode.rst](https://github.com/python-excel/xlrd/blob/master/docs/unicode.rst)

> From Excel 97 onwards, text in Excel spreadsheets has been stored as Unicode

You can't really say this. You're confusing character set and character encoding. Unicode is a character set which can be encoded using several character encoding : UTF-8, UTF-16, UTF-32, and somehow UCS-2 and UCS-4. If I tell you "this file is in Unicode", you won't be able to open and read it, because Unicode is not an actual text encoding. You will have to use one the U-something I told you above. This page need to be somehow reworded. I quickly googled what is the actual encoding of excel files but didn't found.

Microsoft [improperly used the "term" Unicode in its API for years](http://stackoverflow.com/a/3299860), hence why everybody is mistaking. Anyway, it makes no real sense and need to be fixed :).

Hope I made myself clear. Ask me if something is unclear.

**Comment by cjw296** [comment]
That's great, do a pull request which fixes it.

Closing this issue, though, as without a pull request, it won't change.

**Comment by deronnax** [comment]
I don't know the excel file format encoding. As the xl* package maintener,
I was expecting you to know

2016-07-18 17:15 GMT+02:00 Chris Withers <notifications@github.com>:

**Comment by cjw296** [comment]
https://groups.google.com/forum/#!topic/python-excel/P6TjJgFVjMI

**Comment by JulienPalard** [comment]
Whis is this issue even closed? I can't reopen it but it's an actual issue, so as long as it's not fixed, it should be kept open. Should I open another issue to tell this is an actual issue?

**Comment by cjw296** [comment]
@JulienPalard - did you bother to read my comment above? Are you volunteering to do the works to provide a fix along with tests in the form of a pull request?

But sure, if it makes you feel better, I've re-opened the issue.

**Comment by deronnax** [comment]
And you, have you read my comment ? I can make that pull request but I need
to know which encoding is using internally xlrd/wt. I did a quick read but
didn't find anything. If you're the maintainer, answering this question
should take you seconds.

2016-10-31 13:51 GMT+01:00 Chris Withers <notifications@github.com>:

**Comment by cjw296** [comment]
@deronnax - the fact that you have that view suggests you know less than I do - it's not that simple!

**Comment by deronnax** [comment]
I think I found. That's UTF-16LE. In [xlrd/book.py:318-320](https://github.com/python-excel/xlrd/blob/c925847a89f243b9b81341dfa3d9e8e9f1193cb7/xlrd/book.py#L318-L320)
```
  #: An integer denoting the character set used for strings in this file.
  #: For BIFF 8 and later, this will be 1200, meaning Unicode;
  #: more precisely, UTF_16_LE.
```
What do you think ?

**Comment by sjmachin** [comment]
If all you want to know is what range(s) of Unicode characters is/are supported in XLS files (i.e. before Excel 2007), you have the answer.
Note that decoding/encoding is done at a string level, not at a file level.
For detail on how the encoding/decoding works, see xlwt/UnicodeUtils.
