### ISSUE TITLE
Excel NUMBER cell values cast to the good type : INT or FLOAT

### ISSUE THREAD

**Issue by nfork** [python-excel/xlrd#181]
Hi,

By default, XLRD convert all excel number type cell values as float.
The problem is, in python, float displays always the separator, even if it's an integer. 

For example : excel cell value **2016** become **2016.0** in XLRD get rows (sheet.row_values(r))

Idea : implement something like that in native code 

```
if i==int(i):        #checking for the integer: 
  return int(i)      #solving your problem and get the integer 
else:
  return i           #get the float if present
```

**Comment by cjw296** [comment]
Sorry, but the numbers are stored as floating points in the excel file format so this is absolutely not safe to do it.

If it makes sense for your application, please do it there.

**Comment by nfork** [comment]
**1)** I unzip XLSX file and file sheet1.xml and it string like : "**2016**"

![truely](https://cloud.githubusercontent.com/assets/3471584/17857878/c4e0e870-6883-11e6-9d0a-fb764de46191.JPG)

**2)** Why it's not safe ?

I do this : `row[:] = [int(i) if type(i)==float and i == int(i) else i for i in row]`

Moreover many people have this problem :
https://www.google.fr/search?q=xlrd+float+int

**Comment by vadmium** [comment]
I don’t know how large numbers can be in Excel, but your proposal would be a bit strange for cases like

```python
>>> 1e33 == int(1e33)
True
>>> int(1e33)
999999999999999945575230987042816
```
