### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by rocalos2** [python-excel/xlrd#182]
After updated from python 2.6.5-6 to 2.7.6 an error 13 appears.
----------------------------paste---------------------------------------------
Python 2.7.6 (default, Jun 12 2016, 23:31:54)
[GCC 4.9.2] on os2knix
Type "help", "copyright", "credits" or "license" for more information.
>>>import xlrd
>>> import sys
>>> book = xlrd.open_workbook(generadores.xls)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'generadores' is not defined
>>> archivo="generadores.xls"
>>> print archivo
generadores.xls
>>> book = xlrd.open_workbook(archivo)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:/USR/lib/python2.7/site-packages/xlrd/__init__.py", line 435, in open_
workbook
    ragged_rows=ragged_rows,
  File "E:/USR/lib/python2.7/site-packages/xlrd/book.py", line 87, in open_workb
ook_xls
    ragged_rows=ragged_rows,
  File "E:/USR/lib/python2.7/site-packages/xlrd/book.py", line 574, in biff2_8_l
oad
    self.filestr = mmap.mmap(f.fileno(), size, access=mmap.ACCESS_READ)
mmap.error: [Errno 13] Permission denied
>>>
-----------------------------------en of paste-------------------------------------------
Can tell me what is wrong?

Best Regards 
Roberto Calzavara
runing python 2.7.6 under ecomstation 2.2

**Comment by cjw296** [comment]
Suggests you can't read the file. Not convinced that would occur from a python version upgrade.

**Comment by rocalos2** [comment]
I downgrade to 2.6.5-6 and work fine

**Comment by sjmachin** [comment]
Try calling xlrd.open_workbook with use_mmap=1

**Comment by sjmachin** [comment]
DOH!
Try calling xlrd.open_workbook with use_mmap=0

**Comment by rocalos2** [comment]
Work fine with use_mmap=0. 
I change in book.py
---------------paste------------
try:
    import mmap
    MMAP_AVAILABLE = 0
except ImportError:
    MMAP_AVAILABLE = 0
USE_MMAP = MMAP_AVAILABLE
----------end paste-----------------
How can I set this, from my python program?

**Comment by sjmachin** [comment]
import xlrd
xlrd.book.MMAP_AVAILABLE = 0
x = xlrd.open_workbook("foo.xls")

**Comment by cjw296** [comment]
Does the following not work?

```python
x = xlrd.open_workbook("foo.xls", use_mmap=False)
```

**Comment by sjmachin** [comment]
That was my first suggestion. OP's response was "Work fine with use_mmap=0". Closely followed by "How can I set this, from my python program?" which I took to mean wanting a monkey-patch ...

**Comment by cjw296** [comment]
I take it to mean an OP who has no idea what they're doing ;-)
(and should be steered clear of monkey patching!)

Why would memory mapping a file stop working in this way as a result of a Python version upgrade?

**Comment by sjmachin** [comment]
Re py version change: probably caused by some other change that happened at the same time. Getting errno 13 (permission denied) is rather suss -- only read access is required. Note that mmap behaviour depends on the OS in use -- Windows or *x. Read the docs and weep. I have no facilities for *x development. But there was no change of OS version, was there? Conclusion: no monkeys, revert to first suggestion.

**Comment by rocalos2** [comment]
El 22/09/2016 a las 09:00, sjmachin escribió:
>
> Re py version change: probably caused by some other change that 
> happened at the same time. Getting errno 13 (permission denied) is 
> rather suss -- only read access is required. Note that mmap behaviour 
> depends on the OS in use -- Windows or *x. Read the docs and weep. I 
> have no facilities for *x development. But there was no change of OS 
> version, was there? Conclusion: no monkeys, revert to first suggestion.
>
> —
>

I'm using OS/2 operating system (eComstation 2.2) and no change it
Python was ported from linux
 From the  beginning I used Python 2.6xx without problem.
After upgrade to 2.7xxx I get errno 13.
I could solve erron 13 forcing mmap = 0.
I have 4gb ram. OS/2 handling  more then 3gb, have problems. For this I 
think to force mmap=0

**Comment by sjmachin** [comment]
How large is/are the file(s)  you are trying to read?
