### ISSUE TITLE
worksheet.cell_note_map.keys() with different results on different computers

### ISSUE THREAD

**Issue by nnako** [python-excel/xlrd#184]
Hello,

I'm trying to read out comments from a cell within a sheet of a XLSM-Workbook. For this, I use the following sequence of operation on three different computers running Windows and Linux operating systems (WIN7_01, WIN7_02 and LINUX_01). In each case, I use the xlrd module v1.0.0:

``` python
import xlrd

# open EXCEL file to get workbook object
workbook = xlrd.open_workbook( 'testfile.xlsm' )

# get first worksheet object
worksheet = workbook.sheet_by_index(0)

# get list of existing comments within worksheet
_keys = worksheet.cell_note_map.keys()
```

Although the test file `testfile.xlsm`, the `Python version v2.7` and the `xlrd module version v1.0.0` are identical on each of the computers, I get different results as outputs when typing

``` python
print _keys
```

-> on **WIN7_01** and **LINUX_01** I get

``` python
[(33, 278), (34, 73), (43, 136), (33, 138), (33, 179), (44, 381), (44, 199), (33,
 262), (114, 297), (44, 298), (108, 201), (35, 131), (32, 201), (33, 96), (44, 36
1), (32, 250), (36, 111), (107, 201), (32, 237), (33, 209), (53, 291), (42, 279),
 (42, 290), (32, 257), (34, 166), (33, 250), (42, 109), (33, 164), (78, 291), (34
, 188), (89, 68), (51, 291), (33, 167), (42, 45), (43, 45), (44, 181), (44, 335),
 (115, 137), (42, 164), (43, 62), (42, 74), (41, 291), (42, 179), (34, 244), (68,
 206), (44, 234), (42, 199), (79, 291), (44, 263), (115, 291), (44, 187), (33, 10
3), (32, 264), (61, 308), (34, 145), (43, 74), (33, 89), (52, 291), (44, 172), (3
4, 139), (32, 209), (42, 186), (44, 279), (35, 110), (43, 144), (32, 186), (33, 4
4), (33, 187), (32, 194), (34, 63), (35, 73), (33, 73), (59, 291), (33, 130), (44
, 207), (62, 291), (42, 80), (33, 228), (33, 47), (33, 82), (42, 256), (34, 110),
 (42, 60), (33, 290), (32, 278), (33, 152), (74, 208), (43, 291), (73, 215), (33,
 242), (34, 173), (34, 152), (44, 110), (42, 49), (34, 180), (60, 291), (109, 201
), (42, 130), (34, 208), (99, 291), (33, 172), (42, 234), (42, 262), (42, 172), (
115, 300), (33, 237), (44, 167), (42, 146), (42, 283), (116, 139), (32, 285), (34
, 68), (42, 68), (32, 47), (32, 243), (34, 45), (100, 291), (42, 151), (32, 158),
 (43, 109)]
```

-> on **WIN7_02** I get

``` python
[]
```

Is there a hidden dependency on computer environment? Is this problem known? Do you need some further information in order to be able to investigate?

Thanks.

**Comment by nnako** [comment]
Ok, I see, there is not much interest in this issue...

Browsing the WEB I found that XLSM does not seem to be reliably supported by `xlrd` module. And, when I save my workbook as XLS (leaving the innecessary macros), the `worksheet.cell_note_map.keys()` covers all the comments. But as converting from XLSM to XLS reduces the number of possible columns, only the comments of the first valid columns can be read out successfully.

**Is it intended to extend the xlrd functionality to cover XLSM in the near future?** Are there other ways / solutions to read the comments from XLSM files?

**Comment by cjw296** [comment]
No, it is not intended to extend the xlrd functionality to cover XLSM.
