### ISSUE TITLE
xldate_as_tuple not dealing with numbers less then 70 and datemode=0

### ISSUE THREAD

**Issue by aklaver** [python-excel/xlrd#190]
Looking at this issue:
https://github.com/wireservice/csvkit/issues/577

The problem seems to be in xldate_as_tuple()
So:
xldate.xldate_as_tuple(1,0)
---------------------------------------------------------------------------
XLDateAmbiguous                           Traceback (most recent call last)
<ipython-input-28-3695787fc597> in <module>()
----> 1 xldate.xldate_as_tuple(1,0)

/home/aklaver/py_virt/cc_greenhouse_app_py3/lib/python3.4/site-packages/xlrd/xldate.py in xldate_as_tuple(xldate, datemode)
     84 
     85     if xldays < 61 and datemode == 0:
---> 86         raise XLDateAmbiguous(xldate)
     87 
     88     jdn = xldays + _JDN_delta[datemode]

XLDateAmbiguous: 1

Whereas:

`xldate.xldate_as_datetime(1,0)
Out[29]: datetime.datetime(1900, 1, 1, 0, 0)`

The difference being xldate_as_datetime has:

`if datemode:
        epoch = epoch_1904
    else:
        if xldate < 60:
            epoch = epoch_1900
        else:
            # Workaround Excel 1900 leap year bug by adjusting the epoch.
epoch = epoch_1900_minus_1`

**Comment by aklaver** [comment]
This is with xlrd 1.0.0.

**Comment by sjmachin** [comment]
xldate_as_tuple is correct and has been doing that since the dawn of time
xldate_as_datetime has been kludged
