### ISSUE TITLE
got XLRDError while opening xls file created by wps

### ISSUE THREAD

**Issue by attmore** [python-excel/xlrd#191]
i create a xls file using wps and save it as .xls extension file

then, got 
> XLRDError encountered while trying to read file: <FILE_CREATED_BY_WPS>

**Comment by sjmachin** [comment]
Pl;ease supply (1) the minimal Python code (i.e. fewer than 10 lines of code) that you can write to demonstrate the problem (2) the smallest XLS file that demonstrates the problem (3) the full error message and traceback from xlrd

**Comment by jdufresne** [comment]
Closing as the necessary information was not provided.
