### ISSUE TITLE
documentation bug: website produces "SORRY This page does not exist yet"

### ISSUE THREAD

**Issue by jason-s** [python-excel/xlrd#199]
Strange bug in documentation server. If I go to http://xlrd.readthedocs.io/en/latest/index.html sometimes I get a "SORRY This page does not exist yet" error; other times it works fine.

![image](https://cloud.githubusercontent.com/assets/738893/22806301/a6854290-eede-11e6-8e53-2e8ff928a730.png)

**Comment by cjw296** [comment]
I'm afraid that will be something on the Read The Docs guys can fix:
