### ISSUE TITLE
some excel file could not read

### ISSUE THREAD

**Issue by whizzalan** [python-excel/xlrd#200]
Some xls files can read, but some are not.

<img width="878" alt="screen shot 2017-02-14 at 4 36 03 pm" src="https://cloud.githubusercontent.com/assets/5684420/22921313/0182cf52-f2d4-11e6-9183-4912997c5dd7.png">

**Comment by cjw296** [comment]
...and where id that .xls you're trying to open come from?

**Comment by whizzalan** [comment]
@cjw296 What's id means?

**Comment by sjmachin** [comment]
"id" is typo for "is" -- adjacent keys on some keyboards.

**Comment by sjmachin** [comment]
s/id/did

**Comment by whizzalan** [comment]
The problem I find at this row.
<img width="672" alt="screen shot 2017-02-15 at 12 17 30 pm" src="https://cloud.githubusercontent.com/assets/5684420/22960452/cdb45286-f378-11e6-9132-26b341feebf3.png">

[fileLocation](https://drive.google.com/drive/folders/0B0X3Y5T-LbZrQzFnM3lydGE0bVU?usp=sharing)

**Comment by cjw296** [comment]
...and where did that .xls you're trying to open come from?

**Comment by whizzalan** [comment]
uh... I come from a company's crawler results.
Now I want to read into python.

**Comment by cjw296** [comment]
If you want to read into python, I suggest you fix your company's crawler results to generate valid .xls files.

**Comment by whizzalan** [comment]
Java POI packages can read its file directly by each cell.
I will try other packages likely this way.

**Comment by cjw296** [comment]
If you cannot change your company's crawler, then I would suggest you use Java POI to open it!

**Comment by whizzalan** [comment]
@cjw296  Thanks for your reply.
I also found that R packages {XLConnect} solved my problem.
