### ISSUE TITLE
value instead of formula?

### ISSUE THREAD

**Issue by Greymarch** [python-excel/xlrd#206]
I have a 2003 Excel spreadsheet and I am using xlrd to read all the cells in the spreadsheet.  Some of the cells are formulas.  xlrd is returning incorrect data for any cell which contains a formula.  How can I retrieve the correct values for cells which have formulas?   My code correctly retrieves values from any cell which does not have a formula.

**Comment by cjw296** [comment]
This is not a mailing list.
