### ISSUE TITLE
MeetingMessage Objects in Mailbox Break Query Set - WITH SOLUTION

### ISSUE THREAD

**Issue by Afterburned6387** [python-excel/xlrd#210]
# Problem
So here's the problem: If i use a query set on a mailbox that contains meeting invitations (MeetingRequest Items), the query set throws the following exception when it reaches the item because the query set attempts to use "item_id" and "changekey" fields, which are allegedly invalid for the MeetingRequest class

  ```
File "/usr/local/lib/python3.6/site-packages/exchangelib/queryset.py", line 248, in __iter__
    for val in result_formatter(self._query()):
  File "/usr/local/lib/python3.6/site-packages/exchangelib/account.py", line 407, in fetch
    item = validation_folder.item_model_from_tag(i.tag).from_xml(elem=i)
  File "/usr/local/lib/python3.6/site-packages/exchangelib/items.py", line 324, in from_xml
    return cls(item_id=item_id, changekey=changekey, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/exchangelib/items.py", line 127, in __init__
    super(Item, self).__init__(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/exchangelib/properties.py", line 41, in __init__
    raise AttributeError("%s are invalid kwargs for this class" % ', '.join("'%s'" % k for k in kwargs.keys()))
AttributeError: 'item_id', 'changekey' are invalid kwargs for this class
```
It looks like MeetingRequest, MeetingResponse, and Meeting Cancellation are all of class MeetingMessage, and all inherit from Email Message:
[MeetingMessage Class](https://msdn.microsoft.com/en-us/library/microsoft.exchange.webservices.data.meetingmessage(v=exchg.80).aspx)

# Short-Term Solution
Let's have each of the meeting message types follow that inheritance path. In the mean time, to keep query sets from breaking, I'm submitting a merge request that has each MeetingMessage type inherit from Message, and thus should also inherit the 'item_id' and 'change_key' fields.

# Long-Term Solution
We probably need to add a "MeetingMessage" class that each variant (Request, Cancellation, Response) inherits from.

**Comment by sjmachin** [comment]
I don't see any evidence that xlrd is involved here.

**Comment by Afterburned6387** [comment]
Sorry, somehow this got submitted to the wrong repo's issue tracker. I'm a happy xlrd user - no issues there.
