### ISSUE TITLE
open_workbook not working in xlrd 1.0.0

### ISSUE THREAD

**Issue by keshavvprabhu** [python-excel/xlrd#211]
This code used to work fine for me earlier. All of a sudden it stopped working. Any help is appreciated.

**Error Message :** 
C:\Users\blahblah>python csvFromExcel.py Concentration_20170309.xls
['csvFromExcel.py', 'Concentration_20170309.xls']
Traceback (most recent call last):
  File "csvFromExcel.py", line 24, in <module>
    csv_from_excel(sys.argv[1])
  File "csvFromExcel.py", line 9, in csv_from_excel
    workbook = xlrd.open_workbook(excel_file)
  File "C:\Python27\lib\site-packages\xlrd\__init__.py", line 429, in open_workbook
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "C:\Python27\lib\site-packages\xlrd\__init__.py", line 1545, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "C:\Python27\lib\site-packages\xlrd\__init__.py", line 1539, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
xlrd.biffh.XLRDError: Unsupported format, or corrupt file: Expected BOF record; found 'PK\x03\x04\x14\x00\x08\x00'

Code Fragment
# -*- coding: utf-8 -*-
#from xlrd import open_workbook
import xlrd
import csv
import os
import sys

def csv_from_excel(excel_file):
	excel_fname=excel_file.split(".")
	**workbook = xlrd.open_workbook(excel_file)**
	xlFName=excel_fname[0]
	all_worksheets=workbook.sheet_names()
	for worksheet_name in all_worksheets:
		worksheet = workbook.sheet_by_name(worksheet_name)
		newFName=xlFName + "_" + worksheet_name.strip() +".csv"
		print newFName
		your_csv_file = open(newFName, 'wb')
		wr = csv.writer(your_csv_file, quoting=csv.QUOTE_ALL)
		for rownum in xrange(worksheet.nrows):
			wr.writerow([unicode(entry).encode("utf-8") for entry in worksheet.row_values(rownum)])
		your_csv_file.close()

if __name__ == "__main__":
	csv_from_excel(sys.argv[1])

open_workbook(excel_file) is failing for me. 
python --version = 2.7.13
xlrd 1.0.0

**Comment by cjw296** [comment]
This is not a mailing list.
