### ISSUE TITLE
eliminating "blah blah blah" variables throughout the code

### ISSUE THREAD

**Issue by willywutang** [python-excel/xlrd#214]
"blah" is used over 200 times in the codebase. For example, starting on line 827 in book.py:

        blah1 = DEBUG or self.verbosity >= 1
        blah2 = DEBUG or self.verbosity >= 2
        if self.biff_version >= 80:
            num_refs = unpack("<H", data[0:2])[0]
            bytes_reqd = num_refs * 6 + 2
            while len(data) < bytes_reqd:
                if blah1:
                    fprintf(
                        self.logfile,

I suggest using meaningful variable names to make the code easier to read and maintain.

**Comment by cjw296** [comment]
Unlikely to happen, and not functionally a problem, so closing.
