### ISSUE TITLE
LookupError: unknown encoding: unknown_codepage_21010

### ISSUE THREAD

**Issue by acook** [python-excel/xlrd#218]
Codepage 21010 needs to be treated like codepage 1200 (UTF-16le). 

If you don't have time right now just point me to where in the code the mapping needs to be added and I'll see if I can fix it.

**Comment by jdufresne** [comment]
Can you please provide additional details about the issue?

1. Do you have a minimal script that demonstrates the issue?
2. Do you have a minimal xls file to demonstrate the issue?
3. Can you provide a full traceback?

**Comment by acook** [comment]
All that information should be covered in the referenced issue: https://github.com/wireservice/csvkit/issues/859

**Comment by cjw296** [comment]
We'll need a PR to make progress

**Comment by acook** [comment]
Please point me to where in the code the mapping needs to be added and I'll look into it.

**Comment by cjw296** [comment]
Sorry, you'll need to go digging, I don't know where they are.
