### ISSUE TITLE
Wheel file on pypi only supports python 3

### ISSUE THREAD

**Issue by snelson3** [python-excel/xlrd#219]

**Comment by cjw296** [comment]
PR to fix this would be welcome.

**Comment by snelson3** [comment]
There's nothing to Pull Request, because it shouldn't require a code change (it's just the wrong wheel file uploaded to pypi). I was able to generate the correct wheel file by cloning the source code and running "python setup.py sdist bdist_wheel"

**Comment by cjw296** [comment]
Latest release fixes this.
