### ISSUE TITLE
Documentation seems gone :-(

### ISSUE THREAD

**Issue by chunkytrunk** [python-excel/xlrd#222]
Hello,

documentation seems gone - every link not cached by my browser leads to a "maze page" on readthedocs.io. Could you have a look into it, please?

chunkytrunk

**Comment by cjw296** [comment]
How about just clicking on the docs link of the front page of this repo?

**Comment by chunkytrunk** [comment]
If that refers to the button "docs latest" - it leads to the maze site I wrote about.

chunkytrunk

**Comment by cjw296** [comment]
...not for me.

**Comment by cjw296** [comment]
If you're seeing that, sounds like a readthedocs issue, in which case, please file an issue on their tracker, feel free to @mention me...

**Comment by cjw296** [comment]
See https://github.com/rtfd/readthedocs.org/issues/3034.
