### ISSUE TITLE
Shared string with single space stripped

### ISSUE THREAD

**Issue by pwaller** [python-excel/xlrd#225]
Excel renders the following shared string (at the bottom) found in the wild as `hello world`, but when it's read with xlrd it comes out as `helloworld`. The root cause is that the `<t> </t>` tag in the middle lacks a `xml:space="preserve"` and this causes xlrd to strip the space. The stripping causes data loss.

Thinking about the problem for a moment, I propose to add a condition: https://github.com/python-excel/xlrd/blob/e1930e40c02694ef5136e7ace793ccad9a581bd9/xlrd/xlsx.py#L141

Instead, I think this should read:

```python
if elem.get(XML_SPACE_ATTR) != 'preserve' and len(t.strip(XML_WHITESPACE)) > 0:
    t = t.strip(XML_WHITESPACE)
```

The `and len(t.strip(XML_WHITESPACE)) > 1` ensures that if there is an element which only contains whitespace, it is preserved.

Thoughts on the idea? Do you agree that this is a problem and with the direction of the solution? Is there a better way to solve this? If you agree, I'm happy to send a pull request.

# Example broken shared string

This thing is quite unfortunate, but there you have it. It's data stored in Excel for you :(

```xml
<r>
  <rPr>
    <sz val="11"/>
    <color rgb="FF000000"/>
    <rFont val="Calibri"/>
    <family val="2"/>
    <charset val="1"/>
  </rPr>
  <t>hello</t>
</r>
<r>
  <rPr>
    <sz val="7"/>
    <color rgb="FF000000"/>
    <rFont val="Times New Roman"/>
    <family val="1"/>
    <charset val="1"/>
  </rPr>
  <t> </t>
</r>
<r>
  <rPr>
    <sz val="11"/>
    <color rgb="FF000000"/>
    <rFont val="Calibri"/>
    <family val="2"/>
    <charset val="1"/>
  </rPr>
  <t>world</t>
</r>
</si>
```

**Comment by cjw296** [comment]
For xlsx, please use open_pyxl.
