### ISSUE TITLE
Documentation currently not available

### ISSUE THREAD

**Issue by hbast** [python-excel/xlrd#226]
Hey there,
the documentation is currently not working.

http://xlrd.readthedocs.io/en/latest/

Bye, Holger

>         \          SORRY            /
>          \                         /
>           \    This page does     /
>            ]   not exist yet.    [    ,'|
>            ]                     [   /  |
>            ]___               ___[ ,'   |
>            ]  ]\             /[  [ |:   |
>            ]  ] \           / [  [ |:   |
>            ]  ]  ]         [  [  [ |:   |
>            ]  ]  ]__     __[  [  [ |:   |
>            ]  ]  ] ]\ _ /[ [  [  [ |:   |
>            ]  ]  ] ] (#) [ [  [  [ :===='
>            ]  ]  ]_].nHn.[_[  [  [
>            ]  ]  ]  HHHHH. [  [  [
>            ]  ] /   `HH("N  \ [  [
>            ]__]/     HHH  "  \[__[
>            ]         NNN         [
>            ]         N/"         [
>            ]         N H         [
>           /          N            \
>          /           q,            \
>         /                           \

**Comment by cjw296** [comment]
See #222 , which should point to https://github.com/rtfd/readthedocs.org/issues/3034. There's nothing we can do to fix this intermittent issue on the RTD side, you'll just need to upvote the issue I linked to and hope you can persuade them to fix it.

**Comment by hbast** [comment]
seems to be fixed.
