### ISSUE TITLE
ZIP file contents not a known type of workbook

### ISSUE THREAD

**Issue by RobOnMaui** [python-excel/xlrd#228]
I see the first four bytes are PK\x03x04 as XLRD checks on. Is there a work around for this issue or something that can be fixed in XLRD?

Python 3.6.2 (v3.6.2:5fd33b5, Jul  8 2017, 04:14:34) [MSC v.1900 32 bit (Intel)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> import xlrd
>>> file_path = "C:\\client\\files\\raw\\TPS weekly _ W1737.xlsx"
>>> wb = xlrd.open_workbook(filename=file_path,verbosity=5,encoding_override="cp1252",ragged_rows=False)
ZIP component_names:
{'[content_types].xml': '[Content_Types].xml',
 '_rels/.rels': '_rels/.rels',
 '_rels/workbook.xml.rels': '_rels/workbook.xml.rels',
 'styles.xml': 'styles.xml',
 'workbook.xml': 'workbook.xml',
 'worksheet.xml': 'worksheet.xml'}
_Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    wb = xlrd.open_workbook(filename=file_path,verbosity=5,encoding_override="cp1252",ragged_rows=False)
  File "C:\Users\rob.nelson\AppData\Local\Programs\Python\Python36-32\lib\site-packages\xlrd\__init__.py", line 429, in open_workbook
    raise XLRDError('ZIP file contents not a known type of workbook')
xlrd.biffh.XLRDError: ZIP file contents not a known type of workbook_

**Comment by cjw296** [comment]
I'd suggest taking this to the mailing list.
A good workaround is to use openpyxl.
