### ISSUE TITLE
Docs is not work on readthedocs.io

### ISSUE THREAD

**Issue by skyline-gleb** [python-excel/xlrd#229]
http://xlrd.readthedocs.io/en/latest/?badge=latest returns `SORRY This page does not exist yet`

**Comment by cjw296** [comment]
See #222 and #226. Please vote on https://github.com/rtfd/readthedocs.org/issues/3034 or open a new issue there.

**Comment by cjw296** [comment]
Actually, I've opened https://github.com/rtfd/readthedocs.org/issues/3109, please can you upvote.
