### ISSUE TITLE
Documentation missing on xlrd.readthedocs.io

### ISSUE THREAD

**Issue by DavidLutton** [python-excel/xlrd#230]
Documentation missing on [xlrd.readthedocs.io](http://xlrd.readthedocs.io/) says "SORRY This page does not exist yet."

All other documentation linked from [Python-Excel](http://www.python-excel.org/) is available at this time

**Comment by cjw296** [comment]
Please vote on rtfd/readthedocs.org#3109.

**Comment by DavidLutton** [comment]
I can get to the documentation at home, but not at work

**Comment by cjw296** [comment]
It's a common complaint, there's no point telling me though, tell RTD as they're the ones with the problem...

**Comment by liukun** [comment]
JFYI, I can download PDF from https://readthedocs.org/projects/xlrd/downloads/

**Comment by DavidLutton** [comment]
Not an issue at this time
