### ISSUE TITLE
xldate_as_datetime unhandled exception when executed on str value

### ISSUE THREAD

**Issue by cryocaustik** [python-excel/xlrd#231]
looks like there is an unhandled exception when calling `xldate_as_datetime` on a string value, even when the string can be converted to int/float.

example: 
```python
>>> from xlrd.xldate import xldate_as_datetime
>>> x = '42917.00'
>>> xldate_as_datetime(x, 0)
Traceback (most recent call last):
  File "<pyshell#39>", line 1, in <module>
    xldate_as_datetime(x, 0)
  File "C:\Users\cryocaustik\AppData\Local\Programs\Python\Python36\lib\site-packages\xlrd\xldate.py", line 115, in xldate_as_datetime
    if xldate < 60:
TypeError: '<' not supported between instances of 'str' and 'int'
```

possible solutions?: 
1. attempt to convert the str to float/int and then throw an exception when that fails
1. catch when the date supplied is a str and raise an exception then

**Comment by cjw296** [comment]
xldate_as_datetime should not be used on strings.

**Comment by cryocaustik** [comment]
just curious as to why you wouldn't want to handle this? 

you are already converting the `xldate` to an int on line 97:

```python
    if xldate == 0.00:
        return (0, 0, 0, 0, 0, 0)
    if xldate < 0.00:
        raise XLDateNegative(xldate)
    xldays = int(xldate)
```

**Comment by cjw296** [comment]
Why would you? *all* date formatted excel cells are numbers, not strings. If you're passing a string to this function, you're misusing it. Please take this to the mailing lists.
