### ISSUE TITLE
number in text cell is 3 but read out is 3.0

### ISSUE THREAD

**Issue by KOLLSOFT** [python-excel/xlrd#232]
![image](https://user-images.githubusercontent.com/6970682/30964831-89f49dee-a485-11e7-9c23-5fde11f72adc.png)

cell number 3 out is 3.0
but 
cell number 1234 out is 1234

**Comment by cjw296** [comment]
Excel always stores numbers as floats.

**Comment by KOLLSOFT** [comment]
But I set the cell format as Text.

**Comment by KOLLSOFT** [comment]
I solve the problem ’3 can read out 3

**Comment by hprobotic** [comment]
Hi @KOLLSOFT  how can you fix this?. Can you share solution here?
