### ISSUE TITLE
put_cell() can't write into excel

### ISSUE THREAD

**Issue by qyfl** [python-excel/xlrd#233]
import xlrd

excel = xlrd.open_workbook('test.xlsx')
table = excel.sheets()[0]

value = 'hello,world'
table.put_cell(1, 1, 1, value, 0)

when i was open test.xlsx, 'hello,world' is not write into test.xlsx
excel version is 2013

**Comment by qyfl** [comment]
python version is 3.6
xlrd version is 1.1.0

program output is None

**Comment by cjw296** [comment]
This is not a mailing list and xlrd is not used for creating of modifying Excel files.
Use openpyxl.
