### ISSUE TITLE
Specify locale formatting when open_workbook (comma for decimals)

### ISSUE THREAD

**Issue by mberlanda** [python-excel/xlrd#234]
I am doing a very basic usage of this great package for converting `.xlsx` files to `.csv` before to manipulate some data.

In my current implementation I am passing a list of files to this class:

```py
import xlrd
import os
import csv

class CsvConverter():

    def __init__(self,files_dict=None, output_dir=None):
        if not files_dict or not output_dir:
            raise Exception('You should provide files_dict= and output_dir= kwargs')
        self.files_dict = files_dict
        self.output_dir = output_dir
        return

    def execute(self):
        keys = self.files_dict.keys()
        [ self.process_single_file(k) for k in keys ]

    def process_single_file(self, key):
        fp = self.files_dict[key]['full_path']
        workbook = xlrd.open_workbook(fp)
        self.process_wb(key, workbook)

    def process_wb(self, key, workbook):
        sheets = filter(lambda x: x.name == 'sheet', workbook.sheets())
        [ self.write_csv(key, sheet) for sheet in sheets ]

    def write_csv(self, key, sheet):
        with open(os.path.join(self.output_dir, '{}.csv'.format(key)), 'w', newline='') as f:
            writer = csv.writer(f, quoting=csv.QUOTE_ALL, delimiter=';')
            writer.writerows(sheet.row_values(row) for row in range(sheet.nrows))
```

Usage:

```py
files = {
     #...
}
cc = CsvConverter(files_dict=files, output_dir='/')
cc.execute()
```

Since the source files are formatted with Italian Excel locales (*comma for decimals*, optional dot for thousands), all the float written in the csv are incorrect.

E.g. `123,456789` becomes `123456789` instead of `123.4568`

I tried to look around the package implementation, but I could not find where to specify some locale settings.

I don't have any problem with _integers_ and _dates_.

I am parsing `.xslx` with Python 3.6, so I cannot check if `formatting_info=True` would solve this issue.

Would you know any straight forward solution keep using `sheet.row_values(row)` or should I write a custom check for every value?

Thank you in advance

**Comment by cjw296** [comment]
This is not a mailing list
