### ISSUE TITLE
With last row 'merged cell', sheet.nrows differs in macOS and Linux

### ISSUE THREAD

**Issue by zzxwill** [python-excel/xlrd#238]
I used the code below to get all row numbers, but `row_number` differs in macOS and Linux on Python (versioned 2.7). In the [sample.xlsx](https://github.com/python-excel/xlrd/files/1575692/sample.xlsx), last row is in a merged cell.

> book = xlrd.open_workbook(file_name)
> sheet_obj = book.sheet_by_index(0)
> row_number = sheet_obj.nrows

**Comment by cjw296** [comment]
Please use https://openpyxl.readthedocs.io/en/stable/ for xlsx.
