### ISSUE TITLE
Opening a workbook fails to be recognized

### ISSUE THREAD

**Issue by gowdy** [python-excel/xlrd#241]
I've got a patch to fix this. I'll see if I can commit it or send a request. Issue is due to the generated excel file have workbook2.xml instead of the expected workbook.xml.

xlrd.biffh.XLRDError: ZIP file contents not a known type of workbook

**Comment by gowdy** [comment]
I created pull request #242

**Comment by jdufresne** [comment]
As both LibreOffice and openpyxl do not support `workbook2.xml`, I'm not sure this is an issue with xlrd. If you can provide documentation that this is indeed part of the xlsx, I'll quickly change my mind and reopen the issue. At the moment, my first impression is this name may be nonstandard.

If so, might I suggest filing a bug with the data source explaining that they are delivering a nonstandard .xlsx file.

As a last resort, you could unzip and post process the file before passing it to xlrd.

Thanks for the report.

**Comment by jdufresne** [comment]
Can you provide an example file? I think I might understand what is going on. Thanks.

**Comment by cjw296** [comment]
Please use https://openpyxl.readthedocs.io/en/stable/ for xlsx.
