### ISSUE TITLE
cell_note_map empty on Windows 10

### ISSUE THREAD

**Issue by MattiHameister** [python-excel/xlrd#258]
I am using Python 3.6.4 on Linux and Windows 10. I want to read the notes inside a xlsx file. As a test I created a simple [Test.xlsx](https://github.com/python-excel/xlrd/files/1692023/Test.xlsx) file with a note in the first field.

```python
from xlrd import open_workbook

def main():
    workbook = open_workbook("Test.xlsx")
    sheet = workbook.sheets()[0]
    comment_map = sheet.cell_note_map
    print(list(comment_map))

if __name__ == "__main__":
    main()
```

On Linux I get:
> [(0, 0)]

On Windows 10 I get:
> []

It worked on Windows 8 so I don't know what's causing this. Any ideas?

edit: All other data can be read.

**Comment by wenchaoliu2014** [comment]
@MattiHameister 
have you find what's causing this

**Comment by MattiHameister** [comment]
No. It is still an issue sadly.

**Comment by cjw296** [comment]
Please use https://openpyxl.readthedocs.io/en/stable/ for xlsx.
