### ISSUE TITLE
Error opening an excel file with data containing the word 'None'

### ISSUE THREAD

**Issue by nateeee** [python-excel/xlrd#272]
I get this error:
TypeError: expected str, bytes or os.PathLike object, not NoneType
when I attempt to open an excel file that has value None in the cells.  Any way to get around this?

**Comment by jdufresne** [comment]
Can you provide a sample Excel file and simplified script to demonstrate the bug? If possible, please include the full stack trace.

**Comment by nateeee** [comment]
Just realized my error.  I was closing the file handle and then attempting to use xlrd.
