### ISSUE TITLE
Active sheet for XLSX

### ISSUE THREAD

**Issue by cjermain** [python-excel/xlrd#273]
When reading an XLS file, the `Sheet.sheet_selected` attribute is 1 for the "active sheet" that is open when Excel is open. This is consistent with the code notes (below), and exactly what I'm interested in.
https://github.com/python-excel/xlrd/blob/71b15b442266b8f7418babec775c76411cd155da/xlrd/sheet.py#L36-L43

However, for XLSX this attribute is always 0, so I can not identify the "active sheet". I would love to use `xlrd` for reading both XLS and XLSX, but knowing the active sheet is critical. I would prefer not to have to load up the document in another library (like `openpyxl`).

Is this feature within the scope of `xlrd`?

If so, any suggestions as to where to start implementing it? I'm happy to take a crack at it.

**Comment by cjw296** [comment]
Please use openpyxl for xlsx.
