### ISSUE TITLE
unable to read 3rd party xlsx and xls files that have unconventional internal structures

### ISSUE THREAD

**Issue by underthecurve** [python-excel/xlrd#277]
`xlrd` assumes that all xls and xlsx files have an internal structure that use an `xl` subdirectory. This is the case for most but not all Excel files.

For example, xlsx sheets of arrest records produced by the Los Angeles Police Department (using 3rd party tools) do not have an `xl` subdirectory and so cannot be parsed by `xlrd`. I ran into this problem when reporting a story for the L.A. Times, as described here: https://source.opennews.org/articles/how-we-found-new-patterns-la-homeless-arrest/

I tried to open the Excel files in Pandas via `pd.read_excel` (which relies on `xlrd`). Here is the error message:
`XLRDError: ZIP file contents not a known type of workbook`

You can see a sample of the underlying structure of the Excel files here: https://jennybc.github.io/excelgesis/los-angeles-arrests-xlsx/index.html

Note that this [issue](https://github.com/tidyverse/readxl/issues/435) exists in `readxl` from R as well. It has since been patched by @jennybc : https://github.com/tidyverse/readxl/pull/437

Is there a way to make it so that `xlrd` no longer assumes a specific internal structure for Excel files? That way, it would be able to parse these LAPD files (and other "weird" Excel files that have strange internal structures). 

Thank you for looking into this.

**Comment by jennybc** [comment]
> Do you know if they follow the xlsx specification, even if in an unconventional way?

The [readxl PR](https://github.com/tidyverse/readxl/pull/437) gives my assessment of this. TL;DR is that, yes, I think these files follow the minimal spec laid out on pp65-66 ECMA-376 5th edition of *to the letter*. Excel can certainly open them.

Here's the example provided by @underthecurve: https://github.com/tidyverse/readxl/blob/7db09cb017d6f38ab060536968888f5ca2a7192b/tests/testthat/sheets/los-angeles-arrests-xlsx.xlsx 

I am also still curious about what program generates these files.

**Comment by underthecurve** [comment]
I haven't been able to find out, unfortunately. It is definitely an automated program now (in the past the files were sent as text files, by a person).

Let me know if there is anything else I can provide. Thanks.

**Comment by cjw296** [comment]
Please use https://openpyxl.readthedocs.io/en/stable/ for xlsx.
