### ISSUE TITLE
book.__init__ should set self.result. book.result is not set. 

### ISSUE THREAD

**Issue by EvlDave** [python-excel/xlrd#280]
book.result is set to 'None'.  

Documentation says "_result_ should be an instance of the Operand class" but I don't see anything within book.py that sets this.

used in 

```
def area2d(self, clipped=True):
        res = self.result
        if res: 
              ...
``` 
(and in cell() )
e.g.
```
wb = xlrd.open_workbook(path)
rng = wb.name_map[rng_nm][0]
print type(rng) # confirming that I have a xlrd.book.Name
Sheet, rowxlo, rowxhi, colxlo, colxhi = rng.area2d()
```

returns
```
<class 'xlrd.book.Name'>
Traceback (most recent call last):
  File "C:\Python27\xlrdExample.py", line 22, in <module>
    Sheet, rowxlo, rowxhi, colxlo, colxhi = rng.area2d()
  File "C:\Python27\lib\site-packages\xlrd\book.py", line 288, in area2d
    self.dump(self.book.logfile,
AttributeError: 'NoneType' object has no attribute 'logfile'
```

see:
https://stackoverflow.com/questions/24437009/python-xlrd-named-range-value
https://stackoverflow.com/questions/15937493/accessing-the-value-of-the-intersection-of-named-ranges-of-an-excel-spreadsheet/15981179#15981179

the SO references xls vs xlsx, but I haven't seen a difference in behavior between file types.

**Comment by cjw296** [comment]
What documentation are you referring to?
Please work up a PR, closing in the meantime.
