### ISSUE TITLE
open_workbook_2007_xml() got an unexpected keyword argument 'pickleable'

### ISSUE THREAD

**Issue by ghost** [python-excel/xlrd#281]
Hi,
I am trying to read my xlsx file through pandas:
books = pd.ExcelFile('my_file.xlsx')

This is the error:
~/.pyenv/versions/3.6.2/envs/my_env/lib/python3.6/site-packages/pandas/io/excel.py in __init__(self, io, **kwds)
    292             self.book = xlrd.open_workbook(file_contents=data)
    293         elif isinstance(self._io, compat.string_types):
--> 294             self.book = xlrd.open_workbook(self._io)
    295         else:
    296             raise ValueError('Must explicitly set engine if not passing in'

~/.pyenv/versions/3.6.2/envs/my_env/lib/python3.6/site-packages/xlrd/__init__.py in open_workbook(filename, logfile, verbosity, pickleable, use_mmap, file_contents, encoding_override, formatting_info, on_demand, ragged_rows)

TypeError: open_workbook_2007_xml() got an unexpected keyword argument 'pickleable'
Can anyone help? Thanks.

**Comment by cjw296** [comment]
Please use https://openpyxl.readthedocs.io/en/stable/ for xlsx.
