### ISSUE TITLE
How to read a cell and pass if it is empty

### ISSUE THREAD

**Issue by gustavon1973** [python-excel/xlrd#282]
I am copying some cells from one sheet to another sheet and  if a cell is empty it should pass/continue script.

c4 (cell)  is a empty cell.  When I run the code I receive the follwing error:

    self._cell_types[rowx][colx],
IndexError: array index out of range

code:
workbook = xlrd.open_workbook('Username.xls')
sheet = workbook.sheet_by_name('Temp')
c1 = sheet.cell(0, 0).value
print(c1)
worksheet.write(2, 2, str(c1))
c2 = sheet.cell(0, 1)
worksheet.write(3, 2, str(c2.value))
print(c2.value)
c3 = sheet.cell(0, 2)
worksheet.write(4, 2, str(c3.value))
print(c3.value)
c4 = sheet.cell(0, 3)
worksheet.write(5, 2, str(c4.value))
print(c4.value)

**Comment by sbj3** [comment]
Hi. I use the xlrd constants for this.  There are possible two conditions, empty or blank.

```
if  worksheet.cell_type(row_index, 3) != xlrd.XL_CELL_EMPTY and \
        worksheet.cell_type(row_index, 3) != xlrd.XL_CELL_BLANK: 
    # the cell has data
    write... 
```

**Comment by gustavon1973** [comment]
Thanks.  I did that , but received same error:
if sheet.cell_type(0, 3) != xlrd.XL_CELL_EMPTY and sheet.cell_type(0, 3) != xlrd.XL_CELL_BLANK:
    worksheet.write(4, 2, str(c3.value))
    print(sheet.cell_value(0, 3))
else:
    pass

Error:
  File "C:\Python36-32\lib\site-packages\xlrd\sheet.py", line 423, in cell_type
    return self._cell_types[rowx][colx]
IndexError: array index out of range

Am I missing something?

**Comment by cjw296** [comment]
This isn't the mailing list.
