### ISSUE TITLE
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found b'\xb3\xc9\xbd\xbb\xca\xb1\xbc\xe4'

### ISSUE THREAD

**Issue by zixinh** [python-excel/xlrd#286]
```
import urllib.request
import xlrd

dls = 'http://market.finance.sina.com.cn/downxls.php?date=2018-03- 
06&symbol=sh601169'
urllib.request.urlretrieve(dls, "test.xls")

book = xlrd.open_workbook("test.xls")
sheet = book.sheet_by_name("Source")
```

I tried to download a xls file from web but fail to extract it. And I got errors as 
`XLRDError: Unsupported format, or corrupt file: Expected BOF record; found b'\xb3\xc9\xbd\xbb\xca\xb1\xbc\xe4'
`
I've checked xlrd version, which is updated to the newest version. 
Any idea what does 'b'\xb3...' mean and what may go wrong?

Thanks!

**Comment by sali0** [comment]
I'm having the same issue. Downloaded a .xls file and getting the same error.

**Comment by cjw296** [comment]
Tell them to serve you a decent data format. xls is not a decent data format.
