### ISSUE TITLE
time.clock DeprecationWarning

### ISSUE THREAD

**Issue by skhillon** [python-excel/xlrd#294]
Error: `site-packages\xlrd\book.py:130: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  t2 = time.clock()`

Environment Information:
OS - Windows 10
Version - 1.1.0
Installation method - pipenv install xlrd

**Comment by akeeman** [comment]
```
/usr/local/lib/python3.7/site-packages/xlrd/book.py:74: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  t0 = time.clock()

/usr/local/lib/python3.7/site-packages/xlrd/book.py:89: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  t1 = time.clock()

/usr/local/lib/python3.7/site-packages/xlrd/book.py:130: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  t2 = time.clock()
```
xlrd 1.1.0

**Comment by fralau** [comment]
Same issue: `  File "/usr/local/lib/python3.7/site-packages/xlrd-1.1.0-py3.7.egg/xlrd/book.py", line 74, in open_workbook_xls
    t0 = time.clock()
DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead`

On MacOs, Python 3.7.

**Comment by fralau** [comment]
Thanks a lot!

**Comment by adibossiseu** [comment]
@jdufresne Hi Jon! Do you indend to add this fix to the next PyPi release? If so, when it will happen? Thank you :+1:

**Comment by jdufresne** [comment]
Relased 1.2.0 today. Thanks all for the reports and contributes.

https://pypi.org/project/xlrd/1.2.0/

**Comment by adibossiseu** [comment]
Thank you very much, Jon! :+1:
