### ISSUE TITLE
How to get the number of rows of a spreadsheet without considering the hidden cells in xlrd?

### ISSUE THREAD

**Issue by aasiffaizal-weavedin** [python-excel/xlrd#296]
A 1 2 3
B 1 2
C 1 2 3 4 5
ABC are columns
Consider this as the sheet where column C is hidden. Hence if find the nrows using:

nrow = sheet.nrows
it gives nrows as 5. is there anyway to get the number of rows of the file by ignoring the hidden column. I tried slicing the column, col(colx) but still i am getting the length of that object as 5

**Comment by cjw296** [comment]
This is not the mailing list.
