### ISSUE TITLE
Returning bogus value when using cell_value on a cell with value error

### ISSUE THREAD

**Issue by will133** [python-excel/xlrd#301]
I have an excel .xls file with the following:

A1: 2
A2: - (a single dash)
A3: =A1* A2

In excel, the A3 cell will show up as "#VALUE!", an error since it does not know how to interpret the '-'.  However, when xlrd is used to read this, I'd get something like:

```python

In [1]: import xlrd
In [2]: b = xlrd.open_workbook('/home/wlee/bad_excel.xls')
In [3]: s = b.sheets()[0]
In [4]: print s.col_values(0)
[2.0, u'-', 15]
In [5]: print s.cell_value(2, 0)
15
```
It's weird that the return value is an int of 15, which can be extremely confusing since it does not know that an error has occured.  If pyExcelerator is used, I get something like:

```python
In [10]: import pyExcelerator as xl
In [11]: b = xl.parse_xls('bad_excel.xls', 'cp1251')
In [12]: b[0]
(u'Sheet1', {(0, 0): 2.0, (1, 0): u'-', (2, 0): u'#VALUE!'})
```
which I think is more correct since you should not get a random value back.

**Comment by will133** [comment]
I'm using python 2.7 with xlrd version 1.1.0 btw.

**Comment by JeremyPBanks** [comment]
This is normal behavior and not "bogus"; the library uses a dictionary to convert these values if they're pulled, [as documented here](http://www.lexicon.net/sjmachin/xlrd.html#xlrd.error_text_from_code-variable). '#VALUE!' is mapped with 0xF, which is 15 in decimal. If you want to keep it as a string, I'd recommend just making your own dictionary to use while parsing like this:

> errorCheckDict = {0x00:'#NULL!',0x07:'#DIV/0!',0x0F:'#VALUE!',0x17:'#REF!',0x1D:'#NAME?',0x24:'#NUM!',0x2A:'#N/A!'}

At least that's what I did when this came up for me, but maybe there's something built-in to XLRD that I'm not aware of that you could use.

**Comment by will133** [comment]
Thanks for the clarification.  The problem I have is that if I use the col_values, is there a way to know that there is an error vs. the's an actual value of 15 instead?

**Comment by will133** [comment]
The only thing I can think of is test if the value is a isinstance(v, int).  If it's an int I'll use that map to figure out the error string.  Since if it's a number it'll be a floating point number.  However, I can't really just do a error_text_from_code[v] since a float 15.0 would be mapped to the VALUE! error as well.  Do you do the same thing or is there a more reliable way to determine the error?

**Comment by JeremyPBanks** [comment]
When I was using it, the numbers I were working with were much larger, so a 15 would have been some kind of error anyway, so I guess I lucked out, but I see your problem. If that mapping does return an int, than using isinstance is also the best thing I can think of; it's a conditional you'll have to do for every entry, but I think it'll technically get the job done. There may be a better way to do it though, somehow; could be something built-in to the library that I'm not aware of.

**Comment by cjw296** [comment]
Looks like this got resolved.
