### ISSUE TITLE
Assertion Error while reading an .xls file 

### ISSUE THREAD

**Issue by rcoder29** [python-excel/xlrd#302]
In sheet.py file there is a line with assert statement of the function **handle_hlink**
i have a different version of xlrd than what is current, but i noticed that the same code exist in the head version of github sheet.py as well (few lines off)

any suggestions on how to address this from xlrd point of view?
or this is case of a bad xls file that i should get the source regenerate and fix it?

PS - 
I am putting some monkey patching to deal with unicode errors, stopping from reading the files. Seem to me like the current issue is side effect of letting it ignore errors.

xlrd.book.unicode = lambda s, e: s.decode(e, errors="ignore")
xlrd.sheet.unicode = lambda s, e: s.decode(e, errors="ignore")
xlrd.biffh.unicode = lambda s, e: s.decode(e, errors="ignore")

**Comment by rcoder29** [comment]
i am using xlrd version 1.1.0
xlrd                      1.1.0            py36h1cb58dc_1

**Comment by cjw296** [comment]
You have an invalid xls file, sorry.
