### ISSUE TITLE
Error 'unpack requires a string argument of length 2' when opening specific .xls file

### ISSUE THREAD

**Issue by alrusdi** [python-excel/xlrd#303]
Reproduced on either master branch or 1.1.0 stable release.
I use the simplest possible code to open file: [Download sample .xls file here](http://alrusdi.ru/static/bug.xls)

```
import xlrd
wb = xlrd.open_workbook("bug.xlsx")

```
and get this error as result:

```
Traceback (most recent call last):
  File "bug.py", line 2, in <module>
    wb = xlrd.open_workbook("bug.xls")
  File "/home/alrusdi/dev/xlrd/xlrd/__init__.py", line 157, in open_workbook
    ragged_rows=ragged_rows,
  File "/home/alrusdi/dev/xlrd/xlrd/book.py", line 117, in open_workbook_xls
    bk.parse_globals()
  File "/home/alrusdi/dev/xlrd/xlrd/book.py", line 1205, in parse_globals
    self.handle_sst(data)
  File "/home/alrusdi/dev/xlrd/xlrd/book.py", line 1176, in handle_sst
    self._sharedstrings, rt_runlist = unpack_SST_table(strlist, uniquestrings)
  File "/home/alrusdi/dev/xlrd/xlrd/book.py", line 1398, in unpack_SST_table
    nchars = local_unpack('<H', data[pos:pos+2])[0]
struct.error: unpack requires a string argument of length 2
```

If I convert source file with libreoffice:

`libreoffice --convert-to xls bug.xls --outdir ./cvt
`

Then new file (inside cvt directory) is not producing any errors

If I convert source file with gnumeric, I get warning while converting:

`ssconvert bug.xls nobug2.xls
`

```
(ssconvert:5579): libgsf:msole-WARNING **: 13:18:33.099: failure reading block 1 for '\u0005SummaryInformation'

** (ssconvert:5579): WARNING **: 13:18:33.099: Unable to get child['\u0005SummaryInformation'] for infile '?' because : reading block error

```

But result file is just fine (no errors if opened by xlrd and no data loss).

Please consider to fix this bug or provide a workaround to skip this (probably wrong) part of the .xls file while parsing.

**Comment by cjw296** [comment]
Your file is corrupt, if you need to open it with xlrd, you'll have to run it through libreoffice or gnumeric first.
