### ISSUE TITLE
visibility_map, KeyError: 'show', when read a excel file

### ISSUE THREAD

**Issue by mblackcat** [python-excel/xlrd#307]
```
state = elem.get('state')
visibility_map = {
    None: 0,
    'visible': 0,
    'hidden': 1,
    'veryHidden': 2
    }
```

Hello, I notice line 384 in xlsx.py, defined visiblity_map. But in the case I export a excel file by exceljs, which the state is 'show'. (only one sheet in the excel). Then read the file by xlrd, I get error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\xlrd\__init__.py", line 422, in open_workbook

  File "C:\Python27\lib\site-packages\xlrd\xlsx.py", line 765, in open_workbook_2007_xml
    if not tvalue:
  File "C:\Python27\lib\site-packages\xlrd\xlsx.py", line 254, in process_stream

  File "C:\Python27\lib\site-packages\xlrd\xlsx.py", line 376, in do_sheet
    if self.verbosity >= 2:
KeyError: 'show'
```

Is that a bug? The excel file I can open by office success and seems everything's OK.

**Comment by vainu-jussi** [comment]
Bumped in to a same problem with one our clients excel. This one line change seemed to fix it. I can try to submit a pull request for it at some point.


`diff --git a/xlrd/xlsx.py b/xlrd/xlsx.py
index fa1547b..818c41d 100644
--- a/xlrd/xlsx.py
+++ b/xlrd/xlsx.py
@@ -394,7 +394,7 @@ class X12Book(X12General):
             'hidden': 1,
             'veryHidden': 2,
         }
-        bk._sheet_visibility.append(visibility_map[state])
+        bk._sheet_visibility.append(visibility_map.get(state, 0))
         sheet = Sheet(bk, position=None, name=name, number=sheetx)
         sheet.utter_max_rows = X12_MAX_ROWS
         sheet.utter_max_cols = X12_MAX_COLS`

**Comment by cjw296** [comment]
Please use https://openpyxl.readthedocs.io/en/stable/ for xlsx.
