### ISSUE TITLE
Fails to read XLS version=70 cp1251-encoded where XL_LABEL is preceded with 0x98 bytes

### ISSUE THREAD

**Issue by ZVV1971** [python-excel/xlrd#308]
Had to work recently on old .XLS files cp1251-encoded and eventually found out an error caused by str.decode being not able to decode preceding cp-1251 0x98 characters due to errors='strict' setting.
Need either to skip preceding 0x98 or change errors settings.

for those interested the cause is in the R13C14 cell of the attached file

proposed changes to the biffh.py:

lines 246 etc

def unpack_string(data, pos, encoding, lenlen=1):
    nchars = unpack('<' + 'BH'[lenlen-1], data[pos:pos+lenlen])[0]
    pos += lenlen
    if encoding == 'cp1251':
        while data[pos] == 152:
            pos += 1
            nchars -= 1
    return unicode(data[pos:pos+nchars], encoding)

[3176343.zip](https://github.com/python-excel/xlrd/files/2613211/3176343.zip)

**Comment by cjw296** [comment]
Please submit a pull request and refer to this issue.
