### ISSUE TITLE
Use defusedxml directly instead of recommending defuse_stdlib?

### ISSUE THREAD

**Issue by scop** [python-excel/xlrd#320]
docs/vulnerabilities.rst recommends currently using `defusedxml.defuse_stdlib()`. That's documented as experimental and untested in defusedxml, and has the drawback that it affects the entire python runtime, thus possibly breaking things that require features defuse_stdlib disables.

Thus, a more targeted approach, i.e. direct use of defusedxml would be preferable. Would you be interested in a PR that implements this?

**Comment by inclucive-dev1** [comment]
@scop Pls help us file issues at [our repo](https://github.com/inclucive-dev1/xlrdinc/). We have no control (nor response from) this repo. We will fix all outstanding issues for this project at our repo.

**Comment by cjw296** [comment]
@inclusive-dev1 - you haven't really engaged very well. If you can gain my trust, I'd happily let you do work on this repo, ask @jdufresne! You're not off to a good start though.

@scop - my understanding is the stuff disabled is stuff you shouldn't use. Can you give specific examples of the problems you're referring to.

Closing for now.
