### ISSUE TITLE
Excel data reading and passing the data to web application

### ISSUE THREAD

**Issue by rajun897** [python-excel/xlrd#322]
Prepared the .Py file by using XLRD and calling the same in robot framework to fill the data in online application, but i have not succeeded.
My python file is
Import xlrd

    def excelopen(self,filepath,sheetname,functionname):
        workbook = xlrd.open_workbook(filepath, on_demand = True)
        sheet = workbook.sheet_by_name(sheetname)
        #return sheet
        #rowvalue = sheet.cell(row,column)
        for c in sheet.col(0):
            print (c)
            for r in sheet.row(0):    
                print (r)
                print(functionname)
                if c == functionname:
                    print("yes")
                    rowvalues = sheet.row_values(r)
                    print(rowvalues)

Called the same file in robot framework as follows:
excelopen    C:path.xls    Sheet    Login

Excel data as follows:
![image](https://user-images.githubusercontent.com/47881039/53228005-e91ce700-36a5-11e9-95ec-8b894ca706bd.png)

My scenario is search the actions--> relevant row to be copy --> row to be splitted into values.

Please help me on this.

**Comment by cjw296** [comment]
This is not the mailing list.
