### ISSUE TITLE
use stdlib logging instead of print

### ISSUE THREAD

**Issue by srkunze** [python-excel/xlrd#325]
It would be beneficial to use the stdlib logging module to generate log message because third parties can customize/filter the logging output and/or destination.

```
import logging
logger = logging.getLogger(__name__)

logger.info(...)
logger.warn(...)
logger.error(...)
```

**Comment by cjw296** [comment]
The prints are all debugging ones, you can ignore them.

**Comment by srkunze** [comment]
Then please use logger.debug to signify that, so that we can silence them.

Do you accept pull-requests on this?

**Comment by cjw296** [comment]
PRs? Maybe, depends how good they are ;-)

**Comment by cjw296** [comment]
(I mean will stress to you: please use another project, there's little reason to use .xls anymore and openpyxl is a much better place to go for reading xlsx)

**Comment by srkunze** [comment]
> PRs? Maybe, depends how good they are ;-)

I take this as a yes. ;-)

> there's little reason to use .xls anymore

I completely agree with you. Except when sifting through old files, which I do. :-)

I will get back to you in a few minutes with a PR.

**Comment by srkunze** [comment]
After digger deeper, I saw that I can solve my initial issue by using os.devnull

    xlrd.open_workbook(file_path, logfile=open(os.devnull, mode='bw'))

Also a quick look showed that the logfile is passed everywhere I checked (and where it caused trouble). So, actually my problem is solved.
