### ISSUE TITLE
 OverflowError: signed short integer is greater than maximum

### ISSUE THREAD

**Issue by hempalex** [python-excel/xlrd#330]
I'm tried to process this file but got OverflowError.
[1.xls.zip](https://github.com/python-excel/xlrd/files/3109629/1.xls.zip)

xlrd version 1.2.0, python 3.6.8

Full stack trace:
> put_cell 29 2
> Traceback (most recent call last):
>   File "./xls2csv", line 239, in <module>
>     xls2csv(args[0], sys.stdout, **kwargs)
>   File "./xls2csv", line 12, in xls2csv
>     book = xlrd.open_workbook(infilepath, encoding_override=encoding, formatting_info=True)
>   File "/usr/local/lib/python3.6/site-packages/xlrd/__init__.py", line 157, in open_workbook
>     ragged_rows=ragged_rows,
>   File "/usr/local/lib/python3.6/site-packages/xlrd/book.py", line 120, in open_workbook_xls
>     bk.get_sheets()
>   File "/usr/local/lib/python3.6/site-packages/xlrd/book.py", line 723, in get_sheets
>     self.get_sheet(sheetno)
>   File "/usr/local/lib/python3.6/site-packages/xlrd/book.py", line 714, in get_sheet
>     sh.read(self)
>   File "/usr/local/lib/python3.6/site-packages/xlrd/sheet.py", line 812, in read
>     self_put_cell(rowx, colx, XL_CELL_TEXT, bk._sharedstrings[sstindex], xf_index)
>   File "/usr/local/lib/python3.6/site-packages/xlrd/sheet.py", line 706, in put_cell_unragged
>     self._cell_xf_indexes[rowx][colx] = xf_index
> OverflowError: signed short integer is greater than maximum

**Comment by hempalex** [comment]
Same problem with python 2.7.16 and 3.7.3

**Comment by hempalex** [comment]
I've found topic related to this problem
https://groups.google.com/forum/?hl=en-GB#!topic/python-excel/WbotEsQiA8Q

**Comment by cjw296** [comment]
Okay, let's track on the PR
