### ISSUE TITLE
Finding duplicate headers

### ISSUE THREAD

**Issue by Krogsager** [python-excel/xlrd#338]
I was using this code to search for duplicate strings in the header row
header_row is a list of objects of  type`<class 'xlrd.sheet.Cell'>`
E.g. [text:'foo', text:'bar', text:'bas', text:'sikorsky', text:'sikorsky']

```
while len(header_row) >= 0:
    x = header_row.pop()
    if x in header_row:
        print(f"Duplicate found! {x}")
        print("raise error and exit?")
```

I expect the code to print "Duplicate found!" but this does not happen.
Is there a better way to solve this than first calling `.value()` in the Cell object?

```
for header in header_row:
    duplicate_header.append(header.value)
```

**Comment by cjw296** [comment]
This is not the mailing list.
