### ISSUE TITLE
Comments for xlsx not working for Office 365

### ISSUE THREAD

**Issue by MoritzImendoerffer** [python-excel/xlrd#341]
Hi, from the docs I guessed that comments for xlsx should be supported by now. However it seems that the comments are not passed for my xlsx files. Are you aware that parsing comments does not work for all xlsx files (`sel.cell_note_map remains empty`)? Will this be added in future or should I switch to openpyxl ?

**Comment by cjw296** [comment]
For xlsx, please use openpyxl.
