### ISSUE TITLE
xlrd Opening workbook without exception but showing no sheets

### ISSUE THREAD

**Issue by bingyinh** [python-excel/xlrd#343]
Hi,

I got this worksheet that can be opened by xlrd using open_workbook() but showing 0 worksheets.
```
>>> data_file = xlrd.open_workbook('weird_behavior.xlsx')
>>> data_file.sheet_names()
[]
>>> data_file.nsheets
0
```
But Excel can open it and show the worksheet. Not sure what goes wrong. The attachment is the file that shows such weird behavior.
[weird_behavior.xlsx](https://github.com/python-excel/xlrd/files/3262510/weird_behavior.xlsx)

**Comment by cjw296** [comment]
Use openpyxl for xlsx files.
