### ISSUE TITLE
BadZipFile error when using open_workbook on .xlsx

### ISSUE THREAD

**Issue by OD1995** [python-excel/xlrd#344]
Code:
```
A = xlrd.open_workbook(r"K:\Sport\Sponsors\Lookups.xlsx")
```

Error:
```
Traceback (most recent call last):

  File "<ipython-input-7-fd902e6b151e>", line 1, in <module>
    odf = xlrd.open_workbook(lookupsPath)

  File "E:\ANACONDA\lib\site-packages\xlrd\__init__.py", line 117, in open_workbook
    zf = zipfile.ZipFile(filename)

  File "E:\ANACONDA\lib\zipfile.py", line 1131, in __init__
    self._RealGetContents()

  File "E:\ANACONDA\lib\zipfile.py", line 1198, in _RealGetContents
    raise BadZipFile("File is not a zip file")

BadZipFile: File is not a zip file
```

Version:
```
xlrd: 1.2.0
```

**Comment by cjw296** [comment]
Please use openpyxl for xlsx files.

**Comment by OD1995** [comment]
@cjw296  I originally got this issue through pandas - https://github.com/pandas-dev/pandas/issues/26813

**Comment by cjw296** [comment]
I've made the position with xlrd pretty clear to the pandas maintainers:

https://github.com/pandas-dev/pandas/issues/26487 (the issue you closed)
https://github.com/pandas-dev/pandas/issues/11499

It's disappointing that they have not taken this message onboard.

**Comment by OD1995** [comment]
@cjw296 No problem. Apologies, didn't appreciate the context with pandas. Thanks for your replies!
