### ISSUE TITLE
Introduce typing

### ISSUE THREAD

**Issue by vaibhavhrt** [python-excel/xlrd#345]
Since static typing has been introduced in python consider adding type hints to the codebase. In pandas we are adding typing, but since it depends on xlrd we have to ignore all imports from xlrd(and several other third party library) in mypy.
If you consider adding type hints I can help with that. Otherwise I will add type stubs for xlrd in python/typeshed repo, but that requires permission from maintainers of the third party package https://github.com/python/typeshed/blob/master/CONTRIBUTING.md#adding-a-new-library.

So let me know if we are adding typing in xlrd, if not can I have permission to create stubs for it in https://github.com/python/typeshed

**Comment by cjw296** [comment]
I've made the position with xlrd pretty clear to the pandas maintainers:
https://github.com/pandas-dev/pandas/issues/26487#issuecomment-496013360
https://github.com/pandas-dev/pandas/issues/26813#issuecomment-501744823

It continues to be disappointing that you/they have not taken this message onboard.

So no, it's extremely unlikely that xlrd would be introducing type hinting, and I'd really prefer you to focus on removing the dependency of pandas on xlrd, particularly for xlsx files. With that in mind, no you don't have my permission to create stubs for xlrd in typeshed.
