### ISSUE TITLE
Unable to read some 'HTML encoded' XLS files

### ISSUE THREAD

**Issue by paghruli** [python-excel/xlrd#350]
[AccountTransaction-138.zip](https://github.com/python-excel/xlrd/files/3377301/AccountTransaction-138.zip)

I have a set of files which has XLS extension but their contents are HTML. I am able to read many files. But few files gives below error. 

"Unsupported format, or corrupt file: Expected BOF record; found '< div >\r\n\t'"

Attached the file.

**Comment by cjw296** [comment]
These are not xls files, they are html files pretending to be xls files, a hack that used to work to trigger browsers to open Excel, which would then read the html. 

xlrd will never read these, you need to use an html parser.

**Comment by paghruli** [comment]
Thanks. Could you suggest any HTML parser to do this?
