### ISSUE TITLE
expected BOF record; found b'[the fiest character string of the file]

### ISSUE THREAD

**Issue by saif4lingua** [python-excel/xlrd#351]
Hello,
I downloaded an .xls file from IMF as my practice data file, called 'WEO_Data.xls', which can be opened with Microsoft products such as Excel or Power BI. When I tried to open it with xlrd, however,
book = xlrd.open_workbook('WEO_Data.xls'), I've got typical XLRDERROR,
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found b'Country\t'
the last string in the line is the beginning word of the file. It seems that xlrd expects to get some fixed format of string called BOF with this version of xls file but failed to get it. So my guessing is that there should be kinds of xls versions xlrd cannot handle, that those without the BOF flags. If so, can you specify what exact xls version that xlrd can't cover?
the website that downloaded the file is
https://www.imf.org/external/pubs/ft/weo/2019/01/weodata/index.aspx
Thanks

Alvin

**Comment by cjw296** [comment]
That site is lying; it's not an xls file it's serving, so don't expect xlrd to open it.
Try opening it in a text editor, then you're realise it's a tab-separated file that you could open with stdlib's `csv` module.
