### ISSUE TITLE
Why is modifying or updating existing files not supported without copying?

### ISSUE THREAD

**Issue by Farmerjoe12** [python-excel/xlrd#353]
After using java and the Apache POI library for working with Office products, I’m finding the python equivalent libraries to be lacking in comparison. Considering that a .xls file is a .xls file no matter who’s looking at it, why does python (this implementation in particular) have issues with modifying or updating excel workbooks in place? Though it may seem I’m being naive, I understand it’s no trivial task working with a proprietor format and I appreciate the work being done here.

If possible I’d like to figure out what could be done to implement or fix this functionality in xlrd, xlwt, or xlutils. I highly enjoy working with python but the current status of reading and writing is annoying at best and completely broken if any particular formatting is involved.

**Comment by cjw296** [comment]
I'd suggest you should be using xlsx files and, as a result, openpyxl.

**Comment by Farmerjoe12** [comment]
That was completely unhelpful and not constructive in the least.
