### ISSUE TITLE
Python 3.7.4, xlrd 1.2.0

### ISSUE THREAD

**Issue by Maverick494** [python-excel/xlrd#355]
```
  File "d:\python\python37\lib\site-packages\pandas\io\excel\_base.py", line 356, in __init__
    filepath_or_buffer.seek(0)

UnsupportedOperation: seek
```

I found there were previous issues with this, but they don't seem to apply to this version, but I am seeing this problem using pandas.

Here is the snip where I believe this is happening:
```
r = requests.get(projectsExportURL, auth=(username, password), verify=False,stream=True)
r.raw.decode_content = True

df = pd.read_excel(r.raw,sheet_name='Tasks',Headers=0)
```

How do I fix this issue, I can't find a solve.

**Comment by cjw296** [comment]
Are you reading a .xls or .xlsx file?

**Comment by Maverick494** [comment]
> 
> 
> Are you reading a .xls or .xlsx file?

apparently it is now an xlsx

**Comment by cjw296** [comment]
Right, so I'd invite you to go read: 
https://github.com/pandas-dev/pandas/issues/26487
