### ISSUE TITLE
Allow user to choose XML parser

### ISSUE THREAD

**Issue by abielr** [python-excel/xlrd#358]
Would it be possible to add a feature that allows the user to choose which XML library is used to parse XLSX files? Currently in `ensure_elementtree_imported()` I see that libraries are imported in a cascade, starting with `defusedxml`. What I would like to be able to do is manually specify the use of an alternative library. The use case I had in mind was being able to specify `lxml` for faster parsing on large Excel inputs.

**Comment by cjw296** [comment]
Please use openpyxl for reading xlsx files.
