### ISSUE TITLE
Files converted from xlsb to xlsx on mac lose sheets when opened with open_workbook

### ISSUE THREAD

**Issue by jjmgoss** [python-excel/xlrd#359]
When I create an xlsb file in the mac version of excel (on MacOS Mojave Version 10.14.6, Excel for Mac version 16.28 (19081202) ), then re-open it and save it as an xlsx formatted file, then open the xlsx file by calling 
import xlrd
xls = xlrd.open_workbook(filepath)
print(xls.sheet_names())

the sheet_names list is blank.

(using python version 3.6.6, xlrd version 1.2.0)

This doesn't happen when opening the re-saved file in excel, only when opening in xlrd. This is also not a problem with doing the above in windows-based excel.

Please look into why this is happening, especially why it's not a problem for why the sheet names don't disappear when

**Comment by cjw296** [comment]
As you're working with xlsx files, please use openpyxl instead of xlrd.
