### ISSUE TITLE
AssertionError raised in open_workbook

### ISSUE THREAD

**Issue by pyjon** [python-excel/xlrd#53]
xlrd version 0.9.2
Received the following AssertionError when opening the file: https://docs.google.com/viewer?a=v&pid=forums&srcid=MTQ3MzYxMzg3MDQwNjEwOTA5NzQBMDQyNzMwMjUyMDQ0NzU4MTkyMjcBb19PcDdlRm9Rc3NKATQBAXYy&authuser=0

> *** Open failed: AssertionError:
> Traceback (most recent call last):
> File "/usr/bin/runxlrd.py", line 333, in main
> ragged_rows=options.ragged_rows,
> File "/usr/lib64/python2.7/site-packages/xlrd/__init__.py", line 435, in
> open_workbook
> ragged_rows=ragged_rows,
> File "/usr/lib64/python2.7/site-packages/xlrd/book.py", line 116, in
> open_workbook_xls
> bk.parse_globals()
> File "/usr/lib64/python2.7/site-packages/xlrd/book.py", line 1226, in
> parse_globals
> self.names_epilogue()
> File "/usr/lib64/python2.7/site-packages/xlrd/book.py", line 1025, in
> names_epilogue
> evaluate_name_formula(self, nobj, namex, blah=blah)
> File "/usr/lib64/python2.7/site-packages/xlrd/formula.py", line 838, in
> evaluate_name_formula
> do_binop(opcode, stack)
> File "/usr/lib64/python2.7/site-packages/xlrd/formula.py", line 758, in
> do_binop
> assert len(stk) >= 2
> AssertionError

**Comment by cjw296** [comment]
Guess not...

**Comment by rcoder29** [comment]
I am getting same issue with latest version of xlrd, just checking back to see if there is any plans to address this or anyway i can handle this in my code!

line 772, in do_binop
    assert len(stk) >= 2
AssertionError
