### ISSUE TITLE
`assert tvalue is not None`

### ISSUE THREAD

**Issue by SheetJSDev** [python-excel/xlrd#75]
file: http://oss.sheetjs.com/test_files/52348.xlsx

```
$ runxlrd.py 2rows 52348.xlsx

=== File: 52348.xlsx ===
*** Open failed: AssertionError:
Traceback (most recent call last):
  File "/usr/local/bin/runxlrd.py", line 333, in main
    ragged_rows=options.ragged_rows,
  File "/Library/Python/2.7/site-packages/xlrd/__init__.py", line 416, in open_workbook
    ragged_rows=ragged_rows,
  File "/Library/Python/2.7/site-packages/xlrd/xlsx.py", line 754, in open_workbook_2007_xml
    x12sheet.process_stream(zflo, heading)
  File "/Library/Python/2.7/site-packages/xlrd/xlsx.py", line 520, in own_process_stream
    self_do_row(elem)
  File "/Library/Python/2.7/site-packages/xlrd/xlsx.py", line 676, in do_row
    assert tvalue is not None
AssertionError
```

**Comment by jvanbrug** [comment]
Is this resolved? I get the exact same error when I read my Excel file (a 3rd-party export, like @darkosos said) with pandas.read_excel(). However, if I copy/paste all of the cells into a new Excel file, that file can be read fine.

**Comment by cjw296** [comment]
This is a problem in the structure of the original file, so of course copying to a new excel file will work.

**Comment by jvanbrug** [comment]
The assertion seems unnecessary, shouldn't it be altered to handle these almost-readable files? @darkosos's solution works for me,  as does removing the assertion altogether.

**Comment by roozbeh73** [comment]
@jvanbrug, how did you ended up fixing this issue? I have the exact same problem with pandas.read_excel().

**Comment by jmcnamara** [comment]
There is a fix for this issue at #95.

**Comment by cjw296** [comment]
Good, so will be fixed in the next release...

**Comment by jvanbrug** [comment]
@jmcnamara @cjw296 Thanks!

@roozbeh73 I ended up converting the Excel files to CSV (they were simple Excel files) and reading them with `pandas.read_csv()`
