### ISSUE TITLE
Unknown cell type 'd'

### ISSUE THREAD

**Issue by SheetJSDev** [python-excel/xlrd#86]
https://github.com/SheetJS/test_files/blob/master/xlsx-stream-d-date-cell.xlsx

```
    raise Exception("Unknown cell type %r in rowx=%d colx=%d" % (cell_type, rowx, colx))
Exception: Unknown cell type 'd' in rowx=4 colx=1
```

**Comment by cjw296** [comment]
Looks like this should be at least partially fixed in 1.0.1.

If there are further problems, please report them by way of a pull request including unit tests.
