### ISSUE TITLE
*** Open failed: XLRDError: ZIP file contents not a known type of workbook

### ISSUE THREAD

**Issue by SheetJSDev** [python-excel/xlrd#96]
I think this is related to https://github.com/python-excel/xlrd/issues/84

File: http://oss.sheetjs.com/test_files/apachepoi_49609.xlsx

error: `*** Open failed: XLRDError: ZIP file contents not a known type of workbook`

When I manually unzip:

```
$ unzip apachepoi_49609.xlsx
Archive:  apachepoi_49609.xlsx
  inflating: [content_types].xml
warning:  apachepoi_49609.xlsx appears to use backslashes as path separators
```

**Comment by cjw296** [comment]
I think everything related to this has been merged, so this should be good in 1.0.1, maybe even earlier versions.
